// generated by pronto from program.cue — do not edit
// The build graph is authored in program.cue (the build seat) and
// lands here as bayt.json; unifying it back through bayt.#project
// keeps bayt's schema live at generate time.
@extern(embed)

package golaberto

import (
	bayt "github.com/bonisoft3/bayt/core:bayt"
	mecha "github.com/bonisoft3/pronto/clusters:mecha"
	omnishell "github.com/bonisoft3/pronto/terminals:omnishell"
	prontoloop "github.com/bonisoft3/pronto/loops:sayt"
)

// Compiled escape hatches (ir.html: rclone-s3)
// live in program.cue's cluster unification; this redeclaration
// is the out-of-band human override seam (add a cluster target,
// modify one, null to drop one; extend the terminal).
cluster:  mecha.#Cluster
terminal: omnishell.#Terminal
loop:     prontoloop.#Loop

_baytData: _ @embed(file="bayt.json")

project: _golaberto
_golaberto: bayt.#project & _baytData

depManifestsIn: {[string]: _}
_render: (bayt.#render & {project: _golaberto, depManifests: depManifestsIn})
