// generated by pronto from program.cue — do not edit
// The build graph is authored in program.cue (the build seat) and
// lands here as bayt.json; unifying it back through bayt.#project
// keeps bayt's schema live at generate time.
@extern(embed)

package golaberto

import (
	bayt "bonisoft.org/.runtime/plugins/bayt/core:bayt"
	mecha "bonisoft.org/.runtime/plugins/pronto/clusters:mecha"
	omnishell "bonisoft.org/.runtime/plugins/pronto/terminals:omnishell"
	prontoloop "bonisoft.org/.runtime/plugins/pronto/loops:sayt"
)

// Escape hatches: none (ir.html) — the default runtime,
// redeclared unchanged. A program whose ir declares a hatch
// unifies its overrides right here (add a cluster target,
// modify one, null to drop one; extend the terminal).
cluster:  mecha.#Cluster
terminal: omnishell.#Terminal
loop:     prontoloop.#Loop

_baytData: _ @embed(file="bayt.json")

project: _golaberto
_golaberto: bayt.#project & _baytData

depManifestsIn: {[string]: _}
_render: (bayt.#render & {project: _golaberto, depManifests: depManifestsIn})
