// generated by omnishell from the layout this app is built in — do not edit

package golaberto

terminal: surface: {
  runtime: ""
  interpreterRoot: "interpreter"
  componentsRoot: "components"
  markupReader: "read-markup.ts"
  machineSchema: "machine.cue"
}
