// generated by omnishell from the layout this app is built in — do not edit

package golaberto

terminal: surface: {
  runtime: ".runtime/plugins/omnishell/runtime"
  interpreterRoot: ".runtime/plugins/omnishell/interpreter"
  componentsRoot: ".runtime/plugins/omnishell/components"
  markupReader: ".runtime/plugins/omnishell/read-markup.ts"
  machineSchema: ".runtime/plugins/omnishell/machine.cue"
}
