// generated by pronto from the layout this app is built in — do not edit

package golaberto

loop: surface: sources: pronto: ".runtime/plugins/pronto"
build: meta: dir: ""
cluster: meta: root: ""
cluster: meta: runtime: ".runtime/"
