#!/usr/bin/env python3
"""Stage legacy team enrichment and write a reviewable PostgreSQL apply script.

The MySQL connection is read-only. The generated directory contains CSV staging
files and ``apply.sql``; applying that script is a separate operator action.
Comments come from a converted export directory. IDs match the deterministic
archive namespaces: group 4, team 7, appearance 13, user 18, comment 19.
"""

from __future__ import annotations

import argparse
import csv
import datetime as dt
import json
import math
from pathlib import Path
import subprocess
import sys
from typing import Iterable, Iterator


def legacy_uuid(kind: int, legacy_id: int) -> str:
    return f"a{kind:02x}00000-0000-4000-8000-{legacy_id:012x}"


def mysql_rows(query: str) -> Iterator[list[object]]:
    """Yield JSON_ARRAY rows from a consistent, read-only local MySQL snapshot."""
    sql = f"START TRANSACTION WITH CONSISTENT SNAPSHOT, READ ONLY; {query}; COMMIT;"
    proc = subprocess.Popen(
        ["mysql", "-u", "root", "-D", "GolAberto_development", "--batch", "--raw", "--skip-column-names", "-e", sql],
        stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True, encoding="utf-8",
    )
    assert proc.stdout is not None
    for line in proc.stdout:
        yield json.loads(line)
    _, error = proc.communicate()
    if proc.returncode:
        raise RuntimeError(f"read-only MySQL export failed: {error.strip()}")


def yaml_numeric_vector(value: str | None) -> list[float | None]:
    """Read the legacy odds file's simple YAML scalar sequence without PyYAML."""
    if value is None or not value.strip():
        return []
    lines = [line.strip() for line in value.splitlines() if line.strip() and line.strip() != "---"]
    result: list[float | None] = []
    for line in lines:
        if not line.startswith("-"):
            raise ValueError(f"unsupported odds YAML line: {line[:80]!r}")
        token = line[1:].strip()
        if token.lower() in {"null", "~", ""}:
            result.append(None)
            continue
        try:
            number = float(token)
        except ValueError as error:
            raise ValueError(f"invalid odds percentage: {token!r}") from error
        if not math.isfinite(number) or number < 0 or number > 100.000001:
            raise ValueError(f"odds percentage outside [0,100]: {token!r}")
        result.append(min(number, 100.0))
    return result


def comments_from_export(export_dir: Path) -> Iterator[tuple[str, str, str, str, str]]:
    path = export_dir / "comments.ndjson"
    with path.open(encoding="utf-8") as source:
        for line_no, line in enumerate(source, 1):
            legacy_id, team_id, kind, user_id, body, created_at = json.loads(line)
            if kind != "Team":
                continue
            body = str(body or "")
            if not body.strip() or len(body) > 1000:
                raise ValueError(f"{path.name}:{line_no}: team comment is blank or exceeds 1000 characters")
            yield (legacy_uuid(19, int(legacy_id)), legacy_uuid(7, int(team_id)),
                   legacy_uuid(18, int(user_id)), body, str(created_at))


def csv_file(path: Path, header: tuple[str, ...]) -> tuple[csv.writer, object]:
    stream = path.open("x", encoding="utf-8", newline="")
    writer = csv.writer(stream, lineterminator="\n")
    writer.writerow(header)
    return writer, stream


def psql_apply_sql() -> str:
    return r"""-- Generated by tools/import_team_enrichment.py. Review, then run with psql.
-- Run from this directory: psql -v ON_ERROR_STOP=1 -f apply.sql
BEGIN;
SET LOCAL TIME ZONE 'UTC';
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '30min';

CREATE TEMP TABLE _team_geocode_stage(team_id uuid, latitude double precision, longitude double precision) ON COMMIT DROP;
\copy _team_geocode_stage FROM 'team-geocodes.csv' WITH (FORMAT csv, HEADER true)
DO $$ DECLARE skipped bigint; BEGIN
  SELECT count(*) INTO skipped FROM _team_geocode_stage s
  LEFT JOIN public.team t ON t.id=s.team_id WHERE t.id IS NULL;
  RAISE NOTICE 'team coordinates skipped for missing team: %', skipped;
END $$;
UPDATE public.team AS t SET latitude=s.latitude, longitude=s.longitude
FROM _team_geocode_stage AS s WHERE t.id=s.team_id
  AND (t.latitude,t.longitude) IS DISTINCT FROM (s.latitude,s.longitude);

CREATE TEMP TABLE _player_game_rating_stage(id uuid PRIMARY KEY, off_rating double precision, def_rating double precision) ON COMMIT PRESERVE ROWS;
\copy _player_game_rating_stage FROM 'player-game-ratings.csv' WITH (FORMAT csv, HEADER true, NULL '\N')
DO $$ DECLARE skipped bigint; BEGIN
  SELECT count(*) INTO skipped FROM _player_game_rating_stage s
  LEFT JOIN public.player_game p ON p.id=s.id WHERE p.id IS NULL;
  RAISE NOTICE 'appearance ratings skipped for missing player_game: %', skipped;
END $$;
-- Commit small source batches; repeated season changes coalesce in the durable
-- metric queue, which is fully drained before the final import commits.
-- Restarting the script skips equal values; CDC stays enabled throughout.
COMMIT;
CREATE PROCEDURE pg_temp.import_player_ratings() LANGUAGE plpgsql AS $$
DECLARE previous_id uuid:='00000000-0000-0000-0000-000000000000'; last_id uuid; changed integer;
BEGIN
  LOOP
    SELECT id INTO last_id FROM (
      SELECT id FROM _player_game_rating_stage WHERE id>previous_id
      ORDER BY id LIMIT 1000
    ) batch ORDER BY id DESC LIMIT 1;
    EXIT WHEN last_id IS NULL;
    SET LOCAL lock_timeout='5s';
    SET LOCAL statement_timeout='2min';
    UPDATE public.player_game AS p SET off_rating=s.off_rating,def_rating=s.def_rating
    FROM _player_game_rating_stage AS s WHERE p.id=s.id
      AND s.id>previous_id AND s.id<=last_id
      AND (p.off_rating,p.def_rating) IS DISTINCT FROM (s.off_rating,s.def_rating);
    GET DIAGNOSTICS changed=ROW_COUNT;
    COMMIT;
    RAISE NOTICE 'appearance batch through %, changed %',last_id,changed;
    previous_id:=last_id;
    PERFORM pg_sleep(0.1);
  END LOOP;
END $$;
CALL pg_temp.import_player_ratings();
DROP PROCEDURE pg_temp.import_player_ratings();
BEGIN;
SET LOCAL TIME ZONE 'UTC';
SET LOCAL lock_timeout='5s';
SET LOCAL statement_timeout='30min';
-- Acquire the worker lock before touching its queue/projections, so the
-- background refresher cannot take those locks in the opposite order.
SELECT pg_advisory_xact_lock(715029,4);

CREATE TEMP TABLE _team_comment_stage(id uuid, team_id uuid, app_user_id uuid, body text, created_at timestamptz) ON COMMIT DROP;
\copy _team_comment_stage FROM 'team-comments.csv' WITH (FORMAT csv, HEADER true)
DO $$ DECLARE skipped bigint; BEGIN
  SELECT count(*) INTO skipped FROM _team_comment_stage s
  LEFT JOIN public.team t ON t.id=s.team_id
  LEFT JOIN public.app_user u ON u.id=s.app_user_id
  WHERE t.id IS NULL OR u.id IS NULL;
  RAISE NOTICE 'team comments skipped for missing team/user: %', skipped;
END $$;
INSERT INTO public.team_comment AS target(id,team_id,app_user_id,body,created_at)
SELECT s.id,s.team_id,s.app_user_id,s.body,s.created_at FROM _team_comment_stage s
JOIN public.team t ON t.id=s.team_id
JOIN public.app_user u ON u.id=s.app_user_id
ON CONFLICT (id) DO UPDATE SET team_id=EXCLUDED.team_id, app_user_id=EXCLUDED.app_user_id,
  body=EXCLUDED.body, created_at=EXCLUDED.created_at
WHERE (target.team_id,target.app_user_id,target.body,target.created_at)
  IS DISTINCT FROM (EXCLUDED.team_id,EXCLUDED.app_user_id,EXCLUDED.body,EXCLUDED.created_at);

CREATE TEMP TABLE _team_odds_stage(group_id uuid, team_id uuid, recorded_on date, captured_at timestamptz,
  position integer, percent double precision) ON COMMIT DROP;
\copy _team_odds_stage FROM 'team-odds-history.csv' WITH (FORMAT csv, HEADER true, NULL '\N')
DO $$ DECLARE skipped bigint; BEGIN
  SELECT count(*) INTO skipped FROM _team_odds_stage s
  LEFT JOIN public.stage_group g ON g.id=s.group_id
  LEFT JOIN public.team_group m ON m.group_id=s.group_id AND m.team_id=s.team_id
  LEFT JOIN LATERAL (SELECT count(*)::integer AS members FROM public.team_group x WHERE x.group_id=s.group_id) n ON true
  WHERE g.id IS NULL OR m.team_id IS NULL OR s.position > coalesce(n.members,0);
  RAISE NOTICE 'odds cells skipped for missing group/member or out-of-range position: %', skipped;
END $$;
INSERT INTO public.team_odds_history AS target
  (id,group_id,team_id,recorded_on,captured_at,position,percent,source)
SELECT s.group_id::text || ':' || s.team_id::text || ':' || s.recorded_on::text || ':' || s.position::text,
  s.group_id,s.team_id,s.recorded_on,s.captured_at,s.position,s.percent,'imported'
FROM _team_odds_stage s
JOIN public.stage_group g ON g.id=s.group_id
JOIN public.team_group m ON m.group_id=s.group_id AND m.team_id=s.team_id
WHERE s.position <= (SELECT count(*) FROM public.team_group x WHERE x.group_id=s.group_id)
ON CONFLICT (id) DO UPDATE SET captured_at=EXCLUDED.captured_at, percent=EXCLUDED.percent, source='imported'
WHERE (target.captured_at,target.percent,target.source)
  IS DISTINCT FROM (EXCLUDED.captured_at,EXCLUDED.percent,'imported');

-- The durable metric queue is the sole metric writer. Populate rates for
-- unrated legacy seasons too, without taking a stale bulk aggregate snapshot.
INSERT INTO public.player_metric_dirty(player_id,championship_id,revision)
SELECT player_id,championship_id,nextval('public.player_metric_revision_seq')
FROM (SELECT DISTINCT player_id,championship_id FROM public.player_stat WHERE minutes>0 AND goals_per90 IS NULL) missing
ON CONFLICT(player_id,championship_id) DO UPDATE SET revision=EXCLUDED.revision;
DO $$ DECLARE refreshed integer; BEGIN
  LOOP
    SELECT public.refresh_player_metric_queue(1000) INTO refreshed;
    EXIT WHEN refreshed=0;
  END LOOP;
END $$;
DO $$ DECLARE refreshed integer; BEGIN
  LOOP
    SELECT public.refresh_team_profiles(500) INTO refreshed;
    EXIT WHEN refreshed=0;
  END LOOP;
END $$;
DO $$ DECLARE refreshed jsonb; BEGIN
  LOOP
    SELECT public.refresh_team_enrichment(200,100,100) INTO refreshed;
    EXIT WHEN coalesce((refreshed->>'roster_totals')::integer,0)
      + coalesce((refreshed->>'rating_charts')::integer,0)
      + coalesce((refreshed->>'odds_charts')::integer,0)
      + coalesce((refreshed->>'player_metrics')::integer,0)=0;
  END LOOP;
END $$;
COMMIT;
"""


def build(output_dir: Path, export_dir: Path) -> dict[str, int]:
    output_dir.mkdir(parents=True, exist_ok=False)
    counts = {"geocodes": 0, "player_game_ratings": 0, "team_comments": 0,
              "odds_snapshots": 0, "odds_cells": 0, "zero_odds_cells": 0}

    writer, stream = csv_file(output_dir / "team-geocodes.csv", ("team_id", "latitude", "longitude"))
    try:
        query = "SELECT JSON_ARRAY(team_id,JSON_UNQUOTE(JSON_EXTRACT(data,'$[0].lat')),JSON_UNQUOTE(JSON_EXTRACT(data,'$[0].lon'))) FROM team_geocodes ORDER BY team_id"
        for source_id, lat_raw, lon_raw in mysql_rows(query):
            if lat_raw is None or lon_raw is None:
                continue
            latitude, longitude = float(lat_raw), float(lon_raw)
            if not (math.isfinite(latitude) and -90 <= latitude <= 90 and math.isfinite(longitude) and -180 <= longitude <= 180):
                raise ValueError(f"invalid coordinates for legacy team {source_id}")
            writer.writerow((legacy_uuid(7, int(source_id)), latitude, longitude))
            counts["geocodes"] += 1
    finally:
        stream.close()

    writer, stream = csv_file(output_dir / "player-game-ratings.csv", ("id", "off_rating", "def_rating"))
    try:
        query = "SELECT JSON_ARRAY(id,off_rating,def_rating) FROM player_games WHERE off_rating IS NOT NULL OR def_rating IS NOT NULL ORDER BY id"
        for source_id, offense, defense in mysql_rows(query):
            values = [None if offense is None else float(offense), None if defense is None else float(defense)]
            if any(value is not None and not math.isfinite(value) for value in values):
                raise ValueError(f"non-finite player game rating for legacy appearance {source_id}")
            writer.writerow((legacy_uuid(13, int(source_id)), *("\\N" if value is None else value for value in values)))
            counts["player_game_ratings"] += 1
    finally:
        stream.close()

    writer, stream = csv_file(output_dir / "team-comments.csv", ("id", "team_id", "app_user_id", "body", "created_at"))
    try:
        for row in comments_from_export(export_dir):
            identifier, team_id, user_id, body, created_at = row
            stamp = dt.datetime.fromisoformat(created_at.replace("Z", "+00:00"))
            if stamp.tzinfo is None:
                stamp = stamp.replace(tzinfo=dt.timezone.utc)
            writer.writerow((identifier, team_id, user_id, body, stamp.astimezone(dt.timezone.utc).isoformat(timespec="microseconds")))
            counts["team_comments"] += 1
    finally:
        stream.close()

    writer, stream = csv_file(output_dir / "team-odds-history.csv", ("group_id", "team_id", "recorded_on", "captured_at", "position", "percent"))
    try:
        query = """SELECT JSON_ARRAY(tg.group_id,tg.team_id,h.recorded_on,h.captured_at,h.odds)
          FROM team_group_odds_histories h JOIN team_groups tg ON tg.id=h.team_group_id
          ORDER BY h.team_group_id,h.recorded_on,h.captured_at DESC,h.id DESC"""
        previous_day: tuple[int, int, str] | None = None
        for group_legacy, team_legacy, recorded_on, captured_at, odds_yaml in mysql_rows(query):
            day = dt.date.fromisoformat(str(recorded_on)[:10]).isoformat()
            key = (int(group_legacy), int(team_legacy), day)
            # Daily storage keeps the latest capture if the legacy archive has
            # more than one snapshot on a date.
            if key == previous_day:
                continue
            previous_day = key
            vector = yaml_numeric_vector(None if odds_yaml is None else str(odds_yaml))
            if not vector:
                continue
            counts["odds_snapshots"] += 1
            for position, percent in enumerate(vector, 1):
                if percent is None:
                    continue
                writer.writerow((legacy_uuid(4, int(group_legacy)), legacy_uuid(7, int(team_legacy)),
                                 day, str(captured_at) + "Z" if captured_at else "\\N", position, percent))
                counts["odds_cells"] += 1
                counts["zero_odds_cells"] += percent == 0
    finally:
        stream.close()

    (output_dir / "apply.sql").write_text(psql_apply_sql(), encoding="utf-8")
    return counts


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("export_dir", type=Path, help="converted archive directory containing comments.ndjson")
    parser.add_argument("output_dir", type=Path, help="new directory for CSV staging and apply.sql")
    args = parser.parse_args()
    counts = build(args.output_dir, args.export_dir)
    print(json.dumps({**counts, "output_dir": str(args.output_dir),
                      "apply": f"cd {args.output_dir} && psql -v ON_ERROR_STOP=1 -f apply.sql"}, indent=2))
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (ValueError, OSError, KeyError, json.JSONDecodeError, RuntimeError) as error:
        print(f"import_team_enrichment: {error}", file=sys.stderr)
        raise SystemExit(2)
