# Writes pipelines/player-stats_benthos_test.yaml: the player-stats transform
# run over every 2026 Série A player's crawled appearances and goals, asserting
# the line golaberto.com.br's player table shows for each. Two players of one
# name in one squad are left out: a line-up names a player, it does not tell
# two namesakes apart.
#
#   python3 tools/player_stats_fixture.py

import collections
import json

# The transform's place in pipelines/player-stats.yaml.
TRANSFORM = "/pipeline/processors/1/try/7"
FIELDS = ["played", "came_on", "bench", "minutes", "goals", "penalties", "own_goals", "yellow", "red"]
UPSTREAM = {"came_on": "substitute"}

season = json.load(open("tools/crawl/brasileiro2026.json"))
details = {d["upstream"]: d for d in json.load(open("tools/crawl/brasileiro2026-games.json"))}
team_of = {t["upstream"]: t["name"] for t in json.load(open("tools/crawl/teams.json"))}
listed = json.load(open("tools/crawl/players-1523-brasil-campeonato-brasileiro-2026.json"))

apps, goals = collections.defaultdict(list), collections.defaultdict(list)
for g in season:
    d = details.get(g["upstream"])
    if d is None:
        continue
    game = {"home_id": g["home"], "away_id": g["away"], "home": {"name": g["home"]}, "away": {"name": g["away"]}}
    for side in ("home", "away"):
        for p in d[side]:
            apps[(g[side], p["player"])].append({
                "side": side, "on_minute": p["on"], "off_minute": None if p["bench"] else p["off"],
                "yellow": p["yellow"], "red": p["red"], "bench": p["bench"], "game": game})
    for q in d["goals"]:
        # The scorer's own team: the side the goal counts for, or the other one
        # for an own goal.
        scorer = q["side"] if not q["own_goal"] else ("away" if q["side"] == "home" else "home")
        goals[(g[scorer], q["player"])].append({"side": q["side"], "penalty": q["penalty"], "own_goal": q["own_goal"], "game": game})

namesakes = collections.Counter((p["team"], p["name"]) for p in listed)
cases = []
for p in listed:
    key = (team_of[p["team"]], p["name"])
    if namesakes[(p["team"], p["name"])] > 1 or (p["played"] == 0 and p["bench"] == 0):
        continue
    fixture = {"championship": "c", "championship_name": "C", "player": "p", "player_row": {"name": p["name"], "position": None},
               "apps": apps[key], "goals": goals[key]}
    want = [key[0]] + [p[UPSTREAM.get(f, f)] for f in FIELDS]
    cases.append((fixture, want))

with open("pipelines/player-stats_benthos_test.yaml", "w") as f:
    f.write("# generated by tools/player_stats_fixture.py — do not edit\n")
    json.dump({"tests": [{
        "name": f"the 2026 Serie A's {len(cases)} players recount to the lines golaberto.com.br shows",
        "target_processors": TRANSFORM,
        "input_batch": [{"content": json.dumps(fx, ensure_ascii=False)} for fx, _ in cases],
        "output_batches": [[{"bloblang": "this.index(0).rows.map_each(r -> [r.team_id, r.team_name, " + ", ".join(f"r.{x}" for x in FIELDS)
                             + f"]) == [{json.dumps(want[:1] + want, ensure_ascii=False)}]"} for _, want in cases]],
    }, {
        "name": "a scope read names each player and championship once",
        "target_processors": "/pipeline/processors/1/try/1",
        "input_batch": [{"content": json.dumps({"scope": "s", "rows": [
            {"player_id": "p", "game": {"phase": {"championship_id": "c"}}},
            {"player_id": "p", "game": {"phase": {"championship_id": "c"}}},
            {"player_id": "q", "game": {"phase": {"championship_id": "c"}}}]})}],
        "output_batches": [[{"bloblang": 'this == [{"player": "p", "championship": "c"}, {"player": "q", "championship": "c"}]'}]],
    }, {
        "name": "a substitute on in stoppage time and never off has played no negative minutes",
        "target_processors": TRANSFORM,
        "input_batch": [{"content": json.dumps({"championship": "c", "championship_name": "C", "player": "p", "player_row": {"name": "X"},
            "apps": [{"side": "home", "on_minute": 93, "off_minute": None, "yellow": False, "red": False, "bench": False,
                      "game": {"home_id": "h", "away_id": "a", "home": {"name": "H"}, "away": {"name": "A"}}}], "goals": []})}],
        "output_batches": [[{"bloblang": 'this.index(0).rows.index(0).minutes == 0 && this.index(0).rows.index(0).team_name == "H"'}]],
    }, {
        "name": "a deleted game's players are found through their own lines",
        "target_processors": "/pipeline/processors/0",
        "input_batch": [{"content": json.dumps({"data": json.dumps({"__table": "player_game", "id": "x", "player_id": "p", "game_id": "g"})})}],
        "output_batches": [[{"bloblang": 'this.scopes.index(1) == "player_stat?select=player_id,championship_id&player_id=eq.p" && this.player == "p"'}]],
    }, {
        "name": "a deleted goal still names the season it leaves, through its game",
        "target_processors": "/pipeline/processors/0",
        "input_batch": [{"content": json.dumps({"data": json.dumps({"__table": "goal", "id": "x", "player_id": "p", "game_id": "g"})})}],
        "output_batches": [[{"bloblang": 'this.scopes.index(0) == "game?select=phase!inner(championship_id)&id=eq.g" && this.player == "p"'}]],
    }, {
        "name": "a game's read names the event's player in the game's championship",
        "target_processors": "/pipeline/processors/1/try/1",
        "input_batch": [{"content": json.dumps({"scope": "s", "player": "p", "rows": [{"phase": {"championship_id": "c"}}]})}],
        "output_batches": [[{"bloblang": 'this == [{"player": "p", "championship": "c"}]'}]],
    }, {
        "name": "a player with no appearance left, or no row at all, keeps no line",
        "target_processors": TRANSFORM,
        "input_batch": [{"content": json.dumps({"championship": "c", "championship_name": "C", "player": "p", "player_row": {}, "apps": [], "goals": []})}],
        "output_batches": [[{"bloblang": 'this == [{"sink": "delete", "filter": "player_stat?championship_id=eq.c&player_id=eq.p"}]'}]],
    }]}, f, ensure_ascii=False, indent=1)
    f.write("\n")
print(len(cases))
