"""Write the archive fixture without expanding its rows through CUE."""
import collections
import pathlib
import re


def literal(value):
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, str) and "\0" not in value:
        return "'" + value.replace("'", "''") + "'"
    raise ValueError(f"Unsupported seed value: {value!r}")


def render(body):
    sql = [
        "-- generated by tools/seed.py — do not edit",
        "-- Real archive fixtures are loaded only when initializing a fresh database.",
        "SET lock_timeout = '5s';",
        "SET statement_timeout = '60s';",
        "SET standard_conforming_strings = on;",
        "BEGIN;",
    ]
    for entity, rows in body.items():
        table = "stage_group" if entity == "Group" else re.sub(r"(?<!^)(?=[A-Z])", "_", entity).lower()
        if not re.fullmatch(r"[a-z_]+", table):
            raise ValueError(f"Invalid seed entity: {entity}")
        # Omitting a field must still use its database default, not NULL.
        shapes = collections.defaultdict(list)
        for row in rows:
            columns = tuple(sorted(row))
            if "id" not in columns or any(not re.fullmatch(r"[a-z_]+", column) for column in columns):
                raise ValueError(f"Invalid seed columns: {columns}")
            shapes[columns].append(row)
        sql.append(f"-- {entity}: {len(rows)} rows")
        for columns, records in shapes.items():
            for start in range(0, len(records), 500):
                values = ["(" + ", ".join(literal(row[c]) for c in columns) + ")" for row in records[start:start + 500]]
                sql.append(f"INSERT INTO {table} ({', '.join(columns)}) VALUES\n" + ",\n".join(values) + "\nON CONFLICT (id) DO NOTHING;")
    sql.append("COMMIT;")
    return "\n\n".join(sql) + "\n"


def write(body, output):
    pathlib.Path(output).write_text(render(body), encoding="utf-8")
