// generated by pronto from the cel: constraints in program.cue — do not edit
//
// `checks` are the SQL CHECK bodies emit.cue renders into the table DDL;
// `seed` carries what each field-level cel says about the field's own
// value, which is what vets a stated row; `enums` lists the values a
// closed constraint admits, for the readers that cannot enumerate a CUE
// disjunction, and `bounds` states what an open one admits — a range, a
// length, a pattern — for the readers that have to propose a value.
// An invariant binds `this` to the ROW, and a predicate over
// several columns constrains no single field's value, so it derives a
// CHECK body and nothing for CUE.
package golaberto

import "strings"

code: state: entities: {
	AppUser: {
		checks: {
			handle: "char_length(handle) > 0"
		}
		seed: [...{
			handle?: strings.MinRunes(1)
		}]
		bounds: {
			handle: {sizeMin: 1}
		}
	}
	Category: {
		checks: {
			name: "char_length(name) > 0 AND char_length(name) <= 40"
		}
		seed: [...{
			name?: strings.MinRunes(1) & strings.MaxRunes(40)
		}]
		bounds: {
			name: {sizeMin: 1, sizeMax: 40}
		}
	}
	Championship: {
		checks: {
			name: "char_length(name) > 0 AND char_length(name) <= 120"
			region: "region IN ('world', 'continental', 'national')"
			region_name: "char_length(region_name) > 0 AND char_length(region_name) <= 60"
			point_win: "point_win >= 0 AND point_win <= 9"
			point_draw: "point_draw >= 0 AND point_draw <= 9"
			point_loss: "point_loss >= 0 AND point_loss <= 9"
		}
		invariant: check: "ends >= begins"
		seed: [...{
			name?: strings.MinRunes(1) & strings.MaxRunes(120)
			region?: ("world" | "continental" | "national")
			region_name?: strings.MinRunes(1) & strings.MaxRunes(60)
			point_win?: >=0 & <=9
			point_draw?: >=0 & <=9
			point_loss?: >=0 & <=9
		}]
		enums: {
			region: ["world","continental","national"]
		}
		bounds: {
			name: {sizeMin: 1, sizeMax: 120}
			region_name: {sizeMin: 1, sizeMax: 60}
			point_win: {intMin: 0, intMax: 9}
			point_draw: {intMin: 0, intMax: 9}
			point_loss: {intMin: 0, intMax: 9}
		}
	}
	Phase: {
		checks: {
			name: "char_length(name) > 0 AND char_length(name) <= 60"
			position: "position >= 0"
			sort: "sort ~ '^(pt|w|gd|gf|name|g_average|gp|g_aet|head|g_away|bias)(,(pt|w|gd|gf|name|g_average|gp|g_aet|head|g_away|bias))*$'"
			bonus_points: "bonus_points >= 0 AND bonus_points <= 9"
			bonus_points_threshold: "bonus_points_threshold >= 0 AND bonus_points_threshold < 100"
		}
		seed: [...{
			name?: strings.MinRunes(1) & strings.MaxRunes(60)
			position?: >=0
			sort?: =~ "^(pt|w|gd|gf|name|g_average|gp|g_aet|head|g_away|bias)(,(pt|w|gd|gf|name|g_average|gp|g_aet|head|g_away|bias))*$"
			bonus_points?: >=0 & <=9
			bonus_points_threshold?: >=0 & <100
		}]
		bounds: {
			name: {sizeMin: 1, sizeMax: 60}
			position: {intMin: 0}
			sort: {regex: "^(pt|w|gd|gf|name|g_average|gp|g_aet|head|g_away|bias)(,(pt|w|gd|gf|name|g_average|gp|g_aet|head|g_away|bias))*$"}
			bonus_points: {intMin: 0, intMax: 9}
			bonus_points_threshold: {intMin: 0, intMax: 99}
		}
	}
	Group: {
		checks: {
			name: "char_length(name) > 0 AND char_length(name) <= 40"
			position: "position >= 0"
		}
		seed: [...{
			name?: strings.MinRunes(1) & strings.MaxRunes(40)
			position?: >=0
		}]
		bounds: {
			name: {sizeMin: 1, sizeMax: 40}
			position: {intMin: 0}
		}
	}
	Zone: {
		checks: {
			name: "char_length(name) > 0 AND char_length(name) <= 60"
			color: "color IN ('champion', 'promotion', 'qualify', 'playoff', 'relegation')"
			first: "first >= 1"
			last: "last >= 1"
		}
		invariant: check: "last >= first"
		seed: [...{
			name?: strings.MinRunes(1) & strings.MaxRunes(60)
			color?: ("champion" | "promotion" | "qualify" | "playoff" | "relegation")
			first?: >=1
			last?: >=1
		}]
		enums: {
			color: ["champion","promotion","qualify","playoff","relegation"]
		}
		bounds: {
			name: {sizeMin: 1, sizeMax: 60}
			first: {intMin: 1}
			last: {intMin: 1}
		}
	}
	Stadium: {
		checks: {
			name: "char_length(name) > 0 AND char_length(name) <= 80"
			full_name: "char_length(full_name) <= 160"
			city: "char_length(city) <= 80"
			country: "char_length(country) <= 60"
		}
		seed: [...{
			name?: strings.MinRunes(1) & strings.MaxRunes(80)
			full_name?: strings.MaxRunes(160)
			city?: strings.MaxRunes(80)
			country?: strings.MaxRunes(60)
		}]
		bounds: {
			name: {sizeMin: 1, sizeMax: 80}
			full_name: {sizeMax: 160}
			city: {sizeMax: 80}
			country: {sizeMax: 60}
		}
	}
	Team: {
		checks: {
			name: "char_length(name) > 0 AND char_length(name) <= 60"
			full_name: "char_length(full_name) <= 160"
			city: "char_length(city) <= 80"
			country: "char_length(country) > 0 AND char_length(country) <= 60"
			team_type: "team_type IN ('club', 'national')"
		}
		seed: [...{
			name?: strings.MinRunes(1) & strings.MaxRunes(60)
			full_name?: strings.MaxRunes(160)
			city?: strings.MaxRunes(80)
			country?: strings.MinRunes(1) & strings.MaxRunes(60)
			team_type?: ("club" | "national")
		}]
		enums: {
			team_type: ["club","national"]
		}
		bounds: {
			name: {sizeMin: 1, sizeMax: 60}
			full_name: {sizeMax: 160}
			city: {sizeMax: 80}
			country: {sizeMin: 1, sizeMax: 60}
		}
	}
	Referee: {
		checks: {
			name: "char_length(name) > 0 AND char_length(name) <= 80"
			location: "char_length(location) <= 80"
		}
		seed: [...{
			name?: strings.MinRunes(1) & strings.MaxRunes(80)
			location?: strings.MaxRunes(80)
		}]
		bounds: {
			name: {sizeMin: 1, sizeMax: 80}
			location: {sizeMax: 80}
		}
	}
	Player: {
		checks: {
			name: "char_length(name) > 0 AND char_length(name) <= 60"
			full_name: "char_length(full_name) <= 160"
			country: "char_length(country) <= 60"
			height: "height >= 100 AND height <= 230"
			position: "position IN ('g', 'dr', 'dc', 'dl', 'dm', 'cm', 'am', 'fw')"
		}
		seed: [...{
			name?: strings.MinRunes(1) & strings.MaxRunes(60)
			full_name?: strings.MaxRunes(160)
			country?: strings.MaxRunes(60)
			height?: >=100 & <=230
			position?: ("g" | "dr" | "dc" | "dl" | "dm" | "cm" | "am" | "fw")
		}]
		enums: {
			position: ["g","dr","dc","dl","dm","cm","am","fw"]
		}
		bounds: {
			name: {sizeMin: 1, sizeMax: 60}
			full_name: {sizeMax: 160}
			country: {sizeMax: 60}
			height: {intMin: 100, intMax: 230}
		}
	}
	Game: {
		checks: {
			round: "round >= 1 AND round <= 99"
			home_field: "home_field IN ('left', 'neutral', 'right')"
			home_score: "home_score >= 0 AND home_score < 100"
			away_score: "away_score >= 0 AND away_score < 100"
			home_aet: "home_aet >= 0 AND home_aet < 100"
			away_aet: "away_aet >= 0 AND away_aet < 100"
			home_pen: "home_pen >= 0 AND home_pen < 100"
			away_pen: "away_pen >= 0 AND away_pen < 100"
			attendance: "attendance >= 0 AND attendance <= 250000"
		}
		invariant: check: "home_id <> away_id AND played = (home_score IS NOT NULL AND away_score IS NOT NULL) AND (home_score IS NOT NULL) = (away_score IS NOT NULL) AND (home_aet IS NOT NULL) = (away_aet IS NOT NULL) AND (home_pen IS NOT NULL) = (away_pen IS NOT NULL) AND ((home_aet IS NOT NULL) = false OR played) AND ((home_pen IS NOT NULL) = false OR played)"
		seed: [...{
			round?: >=1 & <=99
			home_field?: ("left" | "neutral" | "right")
			home_score?: >=0 & <100
			away_score?: >=0 & <100
			home_aet?: >=0 & <100
			away_aet?: >=0 & <100
			home_pen?: >=0 & <100
			away_pen?: >=0 & <100
			attendance?: >=0 & <=250000
		}]
		enums: {
			home_field: ["left","neutral","right"]
		}
		bounds: {
			round: {intMin: 1, intMax: 99}
			home_score: {intMin: 0, intMax: 99}
			away_score: {intMin: 0, intMax: 99}
			home_aet: {intMin: 0, intMax: 99}
			away_aet: {intMin: 0, intMax: 99}
			home_pen: {intMin: 0, intMax: 99}
			away_pen: {intMin: 0, intMax: 99}
			attendance: {intMin: 0, intMax: 250000}
		}
	}
	Goal: {
		checks: {
			side: "side IN ('home', 'away')"
			minute: "minute >= 0 AND minute <= 130"
		}
		invariant: check: "penalty = false OR own_goal = false"
		seed: [...{
			side?: ("home" | "away")
			minute?: >=0 & <=130
		}]
		enums: {
			side: ["home","away"]
		}
		bounds: {
			minute: {intMin: 0, intMax: 130}
		}
	}
	PlayerGame: {
		checks: {
			side: "side IN ('home', 'away')"
			on_minute: "on_minute >= 0 AND on_minute <= 130"
			off_minute: "off_minute >= 0 AND off_minute <= 130"
		}
		invariant: check: "bench = false OR (on_minute = 0 AND (off_minute IS NOT NULL) = false)"
		seed: [...{
			side?: ("home" | "away")
			on_minute?: >=0 & <=130
			off_minute?: >=0 & <=130
		}]
		enums: {
			side: ["home","away"]
		}
		bounds: {
			on_minute: {intMin: 0, intMax: 130}
			off_minute: {intMin: 0, intMax: 130}
		}
	}
	Standing: {
		checks: {
			position: "position >= 1"
			played: "played >= 0"
			wins: "wins >= 0"
			draws: "draws >= 0"
			losses: "losses >= 0"
			goals_for: "goals_for >= 0"
			goals_against: "goals_against >= 0"
			form1: "form1 IN ('', 'w', 'd', 'l')"
			form2: "form2 IN ('', 'w', 'd', 'l')"
			form3: "form3 IN ('', 'w', 'd', 'l')"
			form4: "form4 IN ('', 'w', 'd', 'l')"
			form5: "form5 IN ('', 'w', 'd', 'l')"
			zone: "zone IN ('', 'champion', 'promotion', 'qualify', 'playoff', 'relegation')"
		}
		seed: [...{
			position?: >=1
			played?: >=0
			wins?: >=0
			draws?: >=0
			losses?: >=0
			goals_for?: >=0
			goals_against?: >=0
			form1?: ("" | "w" | "d" | "l")
			form2?: ("" | "w" | "d" | "l")
			form3?: ("" | "w" | "d" | "l")
			form4?: ("" | "w" | "d" | "l")
			form5?: ("" | "w" | "d" | "l")
			zone?: ("" | "champion" | "promotion" | "qualify" | "playoff" | "relegation")
		}]
		enums: {
			form1: ["","w","d","l"]
			form2: ["","w","d","l"]
			form3: ["","w","d","l"]
			form4: ["","w","d","l"]
			form5: ["","w","d","l"]
			zone: ["","champion","promotion","qualify","playoff","relegation"]
		}
		bounds: {
			position: {intMin: 1}
			played: {intMin: 0}
			wins: {intMin: 0}
			draws: {intMin: 0}
			losses: {intMin: 0}
			goals_for: {intMin: 0}
			goals_against: {intMin: 0}
		}
	}
	TeamChance: {
		checks: {
			rank: "rank >= 1"
			played: "played >= 0"
		}
		seed: [...{
			rank?: >=1
			played?: >=0
		}]
		bounds: {
			rank: {intMin: 1}
			played: {intMin: 0}
		}
	}
	ZoneChance: {
		checks: {
			first: "first >= 1"
			percent: "percent >= 0 AND percent <= 100.5"
			color: "color IN ('champion', 'promotion', 'qualify', 'playoff', 'relegation')"
			band: "band >= 0 AND band <= 4"
			last: "last >= 1"
			reach: "reach IN ('', 'impossible', 'reachable', 'undecided')"
		}
		seed: [...{
			first?: >=1
			percent?: >=0 & <=100.5
			color?: ("champion" | "promotion" | "qualify" | "playoff" | "relegation")
			band?: >=0 & <=4
			last?: >=1
			reach?: ("" | "impossible" | "reachable" | "undecided")
		}]
		enums: {
			color: ["champion","promotion","qualify","playoff","relegation"]
			reach: ["","impossible","reachable","undecided"]
		}
		bounds: {
			first: {intMin: 1}
			percent: {intMin: 0}
			band: {intMin: 0, intMax: 4}
			last: {intMin: 1}
		}
	}
	PositionChance: {
		checks: {
			position: "position >= 1"
			percent: "percent >= 0 AND percent <= 100.5"
			band: "band >= 0 AND band <= 4"
			reach: "reach IN ('', 'impossible', 'reachable', 'undecided')"
		}
		seed: [...{
			position?: >=1
			percent?: >=0 & <=100.5
			band?: >=0 & <=4
			reach?: ("" | "impossible" | "reachable" | "undecided")
		}]
		enums: {
			reach: ["","impossible","reachable","undecided"]
		}
		bounds: {
			position: {intMin: 1}
			percent: {intMin: 0}
			band: {intMin: 0, intMax: 4}
		}
	}
	GameImportance: {
		checks: {
			home: "home >= 0"
			away: "away >= 0"
		}
		seed: [...{
			home?: >=0
			away?: >=0
		}]
		bounds: {
			home: {intMin: 0}
			away: {intMin: 0}
		}
	}
	TeamRating: {
		checks: {
			rating: "rating >= 0 AND rating <= 100"
		}
		seed: [...{
			rating?: >=0 & <=100
		}]
		bounds: {
			rating: {intMin: 0, intMax: 100}
		}
	}
	GameCard: {
		checks: {
			round: "round >= 1 AND round <= 99"
			home_score: "home_score >= 0 AND home_score < 100"
			away_score: "away_score >= 0 AND away_score < 100"
			home_aet: "home_aet >= 0 AND home_aet < 100"
			away_aet: "away_aet >= 0 AND away_aet < 100"
			home_pen: "home_pen >= 0 AND home_pen < 100"
			away_pen: "away_pen >= 0 AND away_pen < 100"
			attendance: "attendance >= 0 AND attendance <= 250000"
			home_upcoming_rank: "home_upcoming_rank >= 0 AND home_upcoming_rank <= 20"
			home_recent_rank: "home_recent_rank >= 0 AND home_recent_rank <= 20"
		}
		seed: [...{
			round?: >=1 & <=99
			home_score?: >=0 & <100
			away_score?: >=0 & <100
			home_aet?: >=0 & <100
			away_aet?: >=0 & <100
			home_pen?: >=0 & <100
			away_pen?: >=0 & <100
			attendance?: >=0 & <=250000
			home_upcoming_rank?: >=0 & <=20
			home_recent_rank?: >=0 & <=20
		}]
		bounds: {
			round: {intMin: 1, intMax: 99}
			home_score: {intMin: 0, intMax: 99}
			away_score: {intMin: 0, intMax: 99}
			home_aet: {intMin: 0, intMax: 99}
			away_aet: {intMin: 0, intMax: 99}
			home_pen: {intMin: 0, intMax: 99}
			away_pen: {intMin: 0, intMax: 99}
			attendance: {intMin: 0, intMax: 250000}
			home_upcoming_rank: {intMin: 0, intMax: 20}
			home_recent_rank: {intMin: 0, intMax: 20}
		}
	}
	TeamGame: {
		checks: {
			side: "side IN ('home', 'away')"
			goals_for: "goals_for >= 0 AND goals_for < 100"
			goals_against: "goals_against >= 0 AND goals_against < 100"
			result: "result IN ('', 'w', 'd', 'l')"
		}
		seed: [...{
			side?: ("home" | "away")
			goals_for?: >=0 & <100
			goals_against?: >=0 & <100
			result?: ("" | "w" | "d" | "l")
		}]
		enums: {
			side: ["home","away"]
			result: ["","w","d","l"]
		}
		bounds: {
			goals_for: {intMin: 0, intMax: 99}
			goals_against: {intMin: 0, intMax: 99}
		}
	}
	Comment: {
		checks: {
			body: "char_length(regexp_replace(body, '^[\\s\\u0085\\u00a0\\u1680\\u2000-\\u200a\\u2028\\u2029\\u202f\\u205f\\u3000]+|[\\s\\u0085\\u00a0\\u1680\\u2000-\\u200a\\u2028\\u2029\\u202f\\u205f\\u3000]+$', '', 'g')) > 0 AND char_length(body) <= 1000"
		}
		seed: [...{
			body?: =~ "[^\\s\\v\\x{85}\\x{a0}\\x{1680}\\x{2000}-\\x{200a}\\x{2028}\\x{2029}\\x{202f}\\x{205f}\\x{3000}]" & strings.MaxRunes(1000)
		}]
		bounds: {
			body: {sizeMin: 1, sizeMax: 1000}
		}
	}
	PlayerStat: {
		checks: {
			position: "position IN ('', 'g', 'dr', 'dc', 'dl', 'dm', 'cm', 'am', 'fw')"
			played: "played >= 0"
			started: "started >= 0"
			came_on: "came_on >= 0"
			bench: "bench >= 0"
			minutes: "minutes >= 0"
			goals: "goals >= 0"
			penalties: "penalties >= 0"
			own_goals: "own_goals >= 0"
			yellow: "yellow >= 0"
			red: "red >= 0"
		}
		seed: [...{
			position?: ("" | "g" | "dr" | "dc" | "dl" | "dm" | "cm" | "am" | "fw")
			played?: >=0
			started?: >=0
			came_on?: >=0
			bench?: >=0
			minutes?: >=0
			goals?: >=0
			penalties?: >=0
			own_goals?: >=0
			yellow?: >=0
			red?: >=0
		}]
		enums: {
			position: ["","g","dr","dc","dl","dm","cm","am","fw"]
		}
		bounds: {
			played: {intMin: 0}
			started: {intMin: 0}
			came_on: {intMin: 0}
			bench: {intMin: 0}
			minutes: {intMin: 0}
			goals: {intMin: 0}
			penalties: {intMin: 0}
			own_goals: {intMin: 0}
			yellow: {intMin: 0}
			red: {intMin: 0}
		}
	}
	PhaseRound: {
		checks: {
			current: "current >= 1"
			next: "next >= 1"
		}
		seed: [...{
			current?: >=1
			next?: >=1
		}]
		bounds: {
			current: {intMin: 1}
			next: {intMin: 1}
		}
	}
	TeamGroup: {
		checks: {
			add_sub: "add_sub >= -99 AND add_sub <= 99"
			bias: "bias >= -99 AND bias <= 99"
			comment: "char_length(comment) <= 500"
		}
		seed: [...{
			add_sub?: >=-99 & <=99
			bias?: >=-99 & <=99
			comment?: strings.MaxRunes(500)
		}]
		bounds: {
			add_sub: {intMin: -99, intMax: 99}
			bias: {intMin: -99, intMax: 99}
			comment: {sizeMax: 500}
		}
	}
	RatingEval: {
		checks: {
			rps: "rps >= 0"
		}
		seed: [...{
			rps?: >=0
		}]
		bounds: {
			rps: {intMin: 0}
		}
	}
	HomeGameCard: {
		checks: {
			round: "round >= 1 AND round <= 99"
			home_score: "home_score >= 0 AND home_score < 100"
			away_score: "away_score >= 0 AND away_score < 100"
			home_aet: "home_aet >= 0 AND home_aet < 100"
			away_aet: "away_aet >= 0 AND away_aet < 100"
			home_pen: "home_pen >= 0 AND home_pen < 100"
			away_pen: "away_pen >= 0 AND away_pen < 100"
			attendance: "attendance >= 0 AND attendance <= 250000"
			home_upcoming_rank: "home_upcoming_rank >= 0 AND home_upcoming_rank <= 20"
			home_recent_rank: "home_recent_rank >= 0 AND home_recent_rank <= 20"
		}
		seed: [...{
			round?: >=1 & <=99
			home_score?: >=0 & <100
			away_score?: >=0 & <100
			home_aet?: >=0 & <100
			away_aet?: >=0 & <100
			home_pen?: >=0 & <100
			away_pen?: >=0 & <100
			attendance?: >=0 & <=250000
			home_upcoming_rank?: >=0 & <=20
			home_recent_rank?: >=0 & <=20
		}]
		bounds: {
			round: {intMin: 1, intMax: 99}
			home_score: {intMin: 0, intMax: 99}
			away_score: {intMin: 0, intMax: 99}
			home_aet: {intMin: 0, intMax: 99}
			away_aet: {intMin: 0, intMax: 99}
			home_pen: {intMin: 0, intMax: 99}
			away_pen: {intMin: 0, intMax: 99}
			attendance: {intMin: 0, intMax: 250000}
			home_upcoming_rank: {intMin: 0, intMax: 20}
			home_recent_rank: {intMin: 0, intMax: 20}
		}
	}
	MatchesGameCard: {
		checks: {
			round: "round >= 1 AND round <= 99"
			home_score: "home_score >= 0 AND home_score < 100"
			away_score: "away_score >= 0 AND away_score < 100"
			home_aet: "home_aet >= 0 AND home_aet < 100"
			away_aet: "away_aet >= 0 AND away_aet < 100"
			home_pen: "home_pen >= 0 AND home_pen < 100"
			away_pen: "away_pen >= 0 AND away_pen < 100"
			attendance: "attendance >= 0 AND attendance <= 250000"
			home_upcoming_rank: "home_upcoming_rank >= 0 AND home_upcoming_rank <= 20"
			home_recent_rank: "home_recent_rank >= 0 AND home_recent_rank <= 20"
		}
		seed: [...{
			round?: >=1 & <=99
			home_score?: >=0 & <100
			away_score?: >=0 & <100
			home_aet?: >=0 & <100
			away_aet?: >=0 & <100
			home_pen?: >=0 & <100
			away_pen?: >=0 & <100
			attendance?: >=0 & <=250000
			home_upcoming_rank?: >=0 & <=20
			home_recent_rank?: >=0 & <=20
		}]
		bounds: {
			round: {intMin: 1, intMax: 99}
			home_score: {intMin: 0, intMax: 99}
			away_score: {intMin: 0, intMax: 99}
			home_aet: {intMin: 0, intMax: 99}
			away_aet: {intMin: 0, intMax: 99}
			home_pen: {intMin: 0, intMax: 99}
			away_pen: {intMin: 0, intMax: 99}
			attendance: {intMin: 0, intMax: 250000}
			home_upcoming_rank: {intMin: 0, intMax: 20}
			home_recent_rank: {intMin: 0, intMax: 20}
		}
	}
	CommentDraft: {
		seed: [...{
			body?: strings.MaxRunes(1000)
			state?: ("writing" | "sending" | "refused")
		}]
		enums: {
			state: ["writing","sending","refused"]
		}
		bounds: {
			body: {sizeMax: 1000}
		}
	}
	GameEdit: {
		seed: [...{
			state?: ("editing" | "saving" | "refused")
			stadium_q?: strings.MaxRunes(80)
			referee_q?: strings.MaxRunes(80)
			stadium_q_key?: strings.MaxRunes(160)
			referee_q_key?: strings.MaxRunes(160)
		}]
		enums: {
			state: ["editing","saving","refused"]
		}
		bounds: {
			stadium_q: {sizeMax: 80}
			referee_q: {sizeMax: 80}
			stadium_q_key: {sizeMax: 160}
			referee_q_key: {sizeMax: 160}
		}
	}
	GamesView: {
		seed: [...{
			id?: strings.MinRunes(1) & strings.MaxRunes(16)
			state?: ("upcoming" | "results")
		}]
		enums: {
			state: ["upcoming","results"]
		}
		bounds: {
			id: {sizeMin: 1, sizeMax: 16}
		}
	}
	DirectoryFilter: {
		seed: [...{
			id?: strings.MinRunes(1) & strings.MaxRunes(16)
			q?: strings.MaxRunes(80)
			state?: ("browsing")
			offset?: >=0
			next_offset?: >=40
			page?: >=1
			country?: strings.MaxRunes(60)
			q_key?: strings.MaxRunes(160)
			country_key?: strings.MaxRunes(120)
		}]
		enums: {
			state: ["browsing"]
		}
		bounds: {
			id: {sizeMin: 1, sizeMax: 16}
			q: {sizeMax: 80}
			offset: {intMin: 0}
			next_offset: {intMin: 40}
			page: {intMin: 1}
			country: {sizeMax: 60}
			q_key: {sizeMax: 160}
			country_key: {sizeMax: 120}
		}
	}
	CatalogFilter: {
		seed: [...{
			id?: strings.MinRunes(1) & strings.MaxRunes(16)
			q?: strings.MaxRunes(80)
			region?: ("" | "world" | "continental" | "national")
			state?: ("browsing")
			offset?: >=0
			next_offset?: >=40
			page?: >=1
			q_key?: strings.MaxRunes(160)
		}]
		enums: {
			region: ["","world","continental","national"]
			state: ["browsing"]
		}
		bounds: {
			id: {sizeMin: 1, sizeMax: 16}
			q: {sizeMax: 80}
			offset: {intMin: 0}
			next_offset: {intMin: 40}
			page: {intMin: 1}
			q_key: {sizeMax: 160}
		}
	}
	ArchivePage: {
		seed: [...{
			offset?: >=0
			next_offset?: >=40
			page?: >=1
			state?: ("browsing")
		}]
		enums: {
			state: ["browsing"]
		}
		bounds: {
			offset: {intMin: 0}
			next_offset: {intMin: 40}
			page: {intMin: 1}
		}
	}
}
