ARG ARCHIVE_DATABASE_BASE
FROM ${ARCHIVE_DATABASE_BASE} AS database
RUN test -f /docker-entrypoint-initdb.d/900_seed.sql \
 && rm /docker-entrypoint-initdb.d/900_seed.sql \
 && test -f /monorepo/services/database/migrations/900_seed.sql \
 && rm /monorepo/services/database/migrations/900_seed.sql
