-- generated by pronto from program.cue — do not edit
SET lock_timeout = '5s';
SET statement_timeout = '60s';

BEGIN;

CREATE TABLE IF NOT EXISTS app_user (
  "id" uuid PRIMARY KEY,
  "handle" portable_string NOT NULL UNIQUE CHECK (char_length(handle) > 0),
  "created_at" portable_timestamp DEFAULT now() NOT NULL,
  "txid" BIGINT DEFAULT pg_current_xact_id()::text::bigint,
  "scope_id" TEXT GENERATED ALWAYS AS ('public:') STORED NOT NULL
);

CREATE TABLE IF NOT EXISTS category (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "name" portable_string NOT NULL UNIQUE CHECK (char_length(name) > 0 AND char_length(name) <= 40),
  "txid" BIGINT DEFAULT pg_current_xact_id()::text::bigint,
  "scope_id" TEXT GENERATED ALWAYS AS ('public:') STORED NOT NULL
);

CREATE TABLE IF NOT EXISTS championship (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "name" portable_string NOT NULL CHECK (char_length(name) > 0 AND char_length(name) <= 120),
  "category_id" uuid REFERENCES category(id) ON DELETE CASCADE,
  "region" portable_string DEFAULT 'national' NOT NULL CHECK (region IN ('world', 'continental', 'national')),
  "region_name" portable_string NOT NULL CHECK (char_length(region_name) > 0 AND char_length(region_name) <= 60),
  "begins" portable_date NOT NULL,
  "ends" portable_date NOT NULL,
  "point_win" portable_int32 DEFAULT 3 NOT NULL CHECK (point_win >= 0 AND point_win <= 9),
  "point_draw" portable_int32 DEFAULT 1 NOT NULL CHECK (point_draw >= 0 AND point_draw <= 9),
  "point_loss" portable_int32 DEFAULT 0 NOT NULL CHECK (point_loss >= 0 AND point_loss <= 9),
  "show_country" portable_bool DEFAULT false NOT NULL,
  "season" portable_string GENERATED ALWAYS AS (extract(year from begins)::int::text || CASE WHEN extract(year from begins) = extract(year from ends) THEN '' ELSE '/' || extract(year from ends)::int::text END) STORED,
  "full_name" portable_string GENERATED ALWAYS AS (region_name || ' - ' || name || ' ' || extract(year from begins)::int::text || CASE WHEN extract(year from begins) = extract(year from ends) THEN '' ELSE '/' || extract(year from ends)::int::text END) STORED,
  "featured" portable_bool DEFAULT false NOT NULL,
  "search_name" portable_string GENERATED ALWAYS AS (region_name || ' - ' || name || ' ' || extract(year from begins)::int::text || CASE WHEN extract(year from begins) = extract(year from ends) THEN '' ELSE '/' || extract(year from ends)::int::text END) STORED,
  "search_key" portable_string GENERATED ALWAYS AS (replace(replace(replace(region_name || ' - ' || name || ' ' || extract(year from begins)::int::text || CASE WHEN extract(year from begins) = extract(year from ends) THEN '' ELSE '/' || extract(year from ends)::int::text END, 'ı', 'i'), 'þ', 'th'), 'Þ', 'th')) STORED,
  "txid" BIGINT DEFAULT pg_current_xact_id()::text::bigint,
  "scope_id" TEXT GENERATED ALWAYS AS ('public:') STORED NOT NULL,
  CHECK (ends >= begins)
);

CREATE TABLE IF NOT EXISTS phase (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "championship_id" uuid NOT NULL REFERENCES championship(id) ON DELETE CASCADE,
  "name" portable_string NOT NULL CHECK (char_length(name) > 0 AND char_length(name) <= 60),
  "position" portable_int32 DEFAULT 0 NOT NULL CHECK (position >= 0),
  "sort" portable_string DEFAULT 'pt,w,gd,gf,gp,g_away,name' NOT NULL CHECK (sort ~ '^(pt|w|gd|gf|name|g_average|gp|g_aet|head|g_away|bias)(,(pt|w|gd|gf|name|g_average|gp|g_aet|head|g_away|bias))*$'),
  "bonus_points" portable_int32 DEFAULT 0 NOT NULL CHECK (bonus_points >= 0 AND bonus_points <= 9),
  "bonus_points_threshold" portable_int32 DEFAULT 0 NOT NULL CHECK (bonus_points_threshold >= 0 AND bonus_points_threshold < 100),
  "txid" BIGINT DEFAULT pg_current_xact_id()::text::bigint,
  "scope_id" TEXT GENERATED ALWAYS AS ('public:') STORED NOT NULL
);

CREATE TABLE IF NOT EXISTS stage_group (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "phase_id" uuid NOT NULL REFERENCES phase(id) ON DELETE CASCADE,
  "name" portable_string NOT NULL CHECK (char_length(name) > 0 AND char_length(name) <= 40),
  "position" portable_int32 DEFAULT 0 NOT NULL CHECK (position >= 0),
  "txid" BIGINT DEFAULT pg_current_xact_id()::text::bigint,
  "scope_id" TEXT GENERATED ALWAYS AS ('public:') STORED NOT NULL
);

CREATE TABLE IF NOT EXISTS zone (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "group_id" uuid NOT NULL REFERENCES stage_group(id) ON DELETE CASCADE,
  "name" portable_string NOT NULL CHECK (char_length(name) > 0 AND char_length(name) <= 60),
  "color" portable_string NOT NULL CHECK (color IN ('champion', 'promotion', 'qualify', 'playoff', 'relegation')),
  "first" portable_int32 NOT NULL CHECK (first >= 1),
  "last" portable_int32 NOT NULL CHECK (last >= 1),
  "txid" BIGINT DEFAULT pg_current_xact_id()::text::bigint,
  "scope_id" TEXT GENERATED ALWAYS AS ('public:') STORED NOT NULL,
  CHECK (last >= first)
);

CREATE TABLE IF NOT EXISTS stadium (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "name" portable_string NOT NULL CHECK (char_length(name) > 0 AND char_length(name) <= 80),
  "full_name" portable_string CHECK (char_length(full_name) <= 160),
  "city" portable_string CHECK (char_length(city) <= 80),
  "country" portable_string CHECK (char_length(country) <= 60),
  "search_name" portable_string GENERATED ALWAYS AS (name) STORED,
  "search_key" portable_string GENERATED ALWAYS AS (replace(replace(replace(name, 'ı', 'i'), 'þ', 'th'), 'Þ', 'th')) STORED,
  "txid" BIGINT DEFAULT pg_current_xact_id()::text::bigint,
  "scope_id" TEXT GENERATED ALWAYS AS ('public:') STORED NOT NULL
);

CREATE TABLE IF NOT EXISTS team (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "name" portable_string NOT NULL CHECK (char_length(name) > 0 AND char_length(name) <= 60),
  "full_name" portable_string CHECK (char_length(full_name) <= 160),
  "city" portable_string CHECK (char_length(city) <= 80),
  "country" portable_string NOT NULL CHECK (char_length(country) > 0 AND char_length(country) <= 60),
  "foundation" portable_date,
  "stadium_id" uuid REFERENCES stadium(id) ON DELETE CASCADE,
  "team_type" portable_string DEFAULT 'club' NOT NULL CHECK (team_type IN ('club', 'national')),
  "foundation_display" portable_string GENERATED ALWAYS AS (lpad(extract(day from foundation)::int::text, 2, '0') || '/' || lpad(extract(month from foundation)::int::text, 2, '0') || '/' || extract(year from foundation)::int::text) STORED,
  "search_name" portable_string GENERATED ALWAYS AS (name) STORED,
  "search_key" portable_string GENERATED ALWAYS AS (replace(replace(replace(name, 'ı', 'i'), 'þ', 'th'), 'Þ', 'th')) STORED,
  "latitude" portable_double CHECK (latitude >= -90 AND latitude <= 90),
  "longitude" portable_double CHECK (longitude >= -180 AND longitude <= 180),
  "txid" BIGINT DEFAULT pg_current_xact_id()::text::bigint,
  "scope_id" TEXT GENERATED ALWAYS AS ('public:') STORED NOT NULL
);

CREATE TABLE IF NOT EXISTS referee (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "name" portable_string NOT NULL CHECK (char_length(name) > 0 AND char_length(name) <= 80),
  "location" portable_string CHECK (char_length(location) <= 80),
  "search_name" portable_string GENERATED ALWAYS AS (name) STORED,
  "search_key" portable_string GENERATED ALWAYS AS (replace(replace(replace(name, 'ı', 'i'), 'þ', 'th'), 'Þ', 'th')) STORED,
  "txid" BIGINT DEFAULT pg_current_xact_id()::text::bigint,
  "scope_id" TEXT GENERATED ALWAYS AS ('public:') STORED NOT NULL
);

CREATE TABLE IF NOT EXISTS player (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "name" portable_string NOT NULL CHECK (char_length(name) > 0 AND char_length(name) <= 60),
  "full_name" portable_string CHECK (char_length(full_name) <= 160),
  "birth" portable_date,
  "country" portable_string CHECK (char_length(country) <= 60),
  "height" portable_int32 CHECK (height >= 100 AND height <= 230),
  "position" portable_string CHECK (position IN ('g', 'dr', 'dc', 'dl', 'dm', 'cm', 'am', 'fw')),
  "txid" BIGINT DEFAULT pg_current_xact_id()::text::bigint,
  "scope_id" TEXT GENERATED ALWAYS AS ('public:') STORED NOT NULL
);

CREATE TABLE IF NOT EXISTS game (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "phase_id" uuid NOT NULL REFERENCES phase(id) ON DELETE CASCADE,
  "round" portable_int32 CHECK (round >= 1 AND round <= 99),
  "day" portable_date NOT NULL,
  "kickoff" portable_timestamp,
  "home_id" uuid NOT NULL REFERENCES team(id) ON DELETE CASCADE,
  "away_id" uuid NOT NULL REFERENCES team(id) ON DELETE CASCADE,
  "home_field" portable_string DEFAULT 'left' NOT NULL CHECK (home_field IN ('left', 'neutral', 'right')),
  "played" portable_bool DEFAULT false NOT NULL,
  "home_score" portable_int32 CHECK (home_score >= 0 AND home_score < 100),
  "away_score" portable_int32 CHECK (away_score >= 0 AND away_score < 100),
  "home_aet" portable_int32 CHECK (home_aet >= 0 AND home_aet < 100),
  "away_aet" portable_int32 CHECK (away_aet >= 0 AND away_aet < 100),
  "home_pen" portable_int32 CHECK (home_pen >= 0 AND home_pen < 100),
  "away_pen" portable_int32 CHECK (away_pen >= 0 AND away_pen < 100),
  "stadium_id" uuid REFERENCES stadium(id) ON DELETE CASCADE,
  "referee_id" uuid REFERENCES referee(id) ON DELETE CASCADE,
  "attendance" portable_int32 CHECK (attendance >= 0 AND attendance <= 250000),
  "day_display" portable_string GENERATED ALWAYS AS (lpad(extract(day from day)::int::text, 2, '0') || '/' || lpad(extract(month from day)::int::text, 2, '0') || '/' || extract(year from day)::int::text) STORED,
  "kickoff_local" portable_string GENERATED ALWAYS AS (CASE WHEN kickoff IS NULL THEN '' ELSE lpad(extract(hour from (kickoff AT TIME ZONE 'America/Sao_Paulo'))::int::text, 2, '0') || ':' || lpad(extract(minute from (kickoff AT TIME ZONE 'America/Sao_Paulo'))::int::text, 2, '0') END) STORED,
  "txid" BIGINT DEFAULT pg_current_xact_id()::text::bigint,
  "scope_id" TEXT GENERATED ALWAYS AS ('public:') STORED NOT NULL,
  CHECK (home_id <> away_id AND played = (home_score IS NOT NULL AND away_score IS NOT NULL) AND (home_score IS NOT NULL) = (away_score IS NOT NULL) AND (home_aet IS NOT NULL) = (away_aet IS NOT NULL) AND (home_pen IS NOT NULL) = (away_pen IS NOT NULL) AND ((home_aet IS NOT NULL) = false OR played) AND ((home_pen IS NOT NULL) = false OR played))
);

CREATE TABLE IF NOT EXISTS goal (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "game_id" uuid NOT NULL REFERENCES game(id) ON DELETE CASCADE,
  "player_id" uuid NOT NULL REFERENCES player(id) ON DELETE CASCADE,
  "side" portable_string NOT NULL CHECK (side IN ('home', 'away')),
  "minute" portable_int32 CHECK (minute >= 0 AND minute <= 130),
  "penalty" portable_bool DEFAULT false NOT NULL,
  "own_goal" portable_bool DEFAULT false NOT NULL,
  "aet" portable_bool DEFAULT false NOT NULL,
  "txid" BIGINT DEFAULT pg_current_xact_id()::text::bigint,
  "scope_id" TEXT GENERATED ALWAYS AS ('public:') STORED NOT NULL,
  CHECK (penalty = false OR own_goal = false)
);

CREATE TABLE IF NOT EXISTS player_game (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "game_id" uuid NOT NULL REFERENCES game(id) ON DELETE CASCADE,
  "player_id" uuid NOT NULL REFERENCES player(id) ON DELETE CASCADE,
  "side" portable_string NOT NULL CHECK (side IN ('home', 'away')),
  "on_minute" portable_int32 DEFAULT 0 NOT NULL CHECK (on_minute >= 0 AND on_minute <= 130),
  "off_minute" portable_int32 CHECK (off_minute >= 0 AND off_minute <= 130),
  "yellow" portable_bool DEFAULT false NOT NULL,
  "red" portable_bool DEFAULT false NOT NULL,
  "bench" portable_bool DEFAULT false NOT NULL,
  "day" portable_date,
  "day_display" portable_string GENERATED ALWAYS AS (lpad(extract(day from day)::int::text, 2, '0') || '/' || lpad(extract(month from day)::int::text, 2, '0') || '/' || extract(year from day)::int::text) STORED,
  "off_rating" portable_double,
  "def_rating" portable_double,
  "txid" BIGINT DEFAULT pg_current_xact_id()::text::bigint,
  "scope_id" TEXT GENERATED ALWAYS AS ('public:') STORED NOT NULL,
  CHECK (bench = false OR (on_minute = 0 AND (off_minute IS NOT NULL) = false))
);

CREATE TABLE IF NOT EXISTS standing (
  "id" portable_string PRIMARY KEY,
  "group_id" uuid NOT NULL REFERENCES stage_group(id) ON DELETE CASCADE,
  "team_id" uuid NOT NULL REFERENCES team(id) ON DELETE CASCADE,
  "team_name" portable_string NOT NULL,
  "position" portable_int32 NOT NULL CHECK (position >= 1),
  "points" portable_int32 NOT NULL,
  "played" portable_int32 NOT NULL CHECK (played >= 0),
  "wins" portable_int32 NOT NULL CHECK (wins >= 0),
  "draws" portable_int32 NOT NULL CHECK (draws >= 0),
  "losses" portable_int32 NOT NULL CHECK (losses >= 0),
  "goals_for" portable_int32 NOT NULL CHECK (goals_for >= 0),
  "goals_against" portable_int32 NOT NULL CHECK (goals_against >= 0),
  "goal_diff" portable_int32 NOT NULL,
  "form1" portable_string NOT NULL CHECK (form1 IN ('', 'w', 'd', 'l')),
  "form2" portable_string NOT NULL CHECK (form2 IN ('', 'w', 'd', 'l')),
  "form3" portable_string NOT NULL CHECK (form3 IN ('', 'w', 'd', 'l')),
  "form4" portable_string NOT NULL CHECK (form4 IN ('', 'w', 'd', 'l')),
  "form5" portable_string NOT NULL CHECK (form5 IN ('', 'w', 'd', 'l')),
  "zone" portable_string NOT NULL CHECK (zone IN ('', 'champion', 'promotion', 'qualify', 'playoff', 'relegation')),
  "txid" BIGINT DEFAULT pg_current_xact_id()::text::bigint,
  "scope_id" TEXT GENERATED ALWAYS AS ('public:') STORED NOT NULL
);

CREATE TABLE IF NOT EXISTS team_chance (
  "id" uuid PRIMARY KEY,
  "group_id" uuid NOT NULL REFERENCES stage_group(id) ON DELETE CASCADE,
  "team_id" uuid NOT NULL REFERENCES team(id) ON DELETE CASCADE,
  "team_name" portable_string NOT NULL,
  "rank" portable_int32 NOT NULL CHECK (rank >= 1),
  "points" portable_int32 NOT NULL,
  "played" portable_int32 NOT NULL CHECK (played >= 0),
  "txid" BIGINT DEFAULT pg_current_xact_id()::text::bigint,
  "scope_id" TEXT GENERATED ALWAYS AS ('public:') STORED NOT NULL
);

CREATE TABLE IF NOT EXISTS zone_chance (
  "id" uuid PRIMARY KEY,
  "group_id" uuid NOT NULL REFERENCES stage_group(id) ON DELETE CASCADE,
  "team_id" uuid NOT NULL REFERENCES team(id) ON DELETE CASCADE,
  "zone_id" uuid NOT NULL REFERENCES zone(id) ON DELETE CASCADE,
  "first" portable_int32 NOT NULL CHECK (first >= 1),
  "percent" portable_double NOT NULL CHECK (percent >= 0 AND percent <= 100.5),
  "color" portable_string NOT NULL CHECK (color IN ('champion', 'promotion', 'qualify', 'playoff', 'relegation')),
  "band" portable_int32 NOT NULL CHECK (band >= 0 AND band <= 4),
  "last" portable_int32 NOT NULL CHECK (last >= 1),
  "reach" portable_string NOT NULL CHECK (reach IN ('', 'impossible', 'reachable', 'undecided')),
  "txid" BIGINT DEFAULT pg_current_xact_id()::text::bigint,
  "scope_id" TEXT GENERATED ALWAYS AS ('public:') STORED NOT NULL
);

CREATE TABLE IF NOT EXISTS position_chance (
  "id" uuid PRIMARY KEY,
  "group_id" uuid NOT NULL REFERENCES stage_group(id) ON DELETE CASCADE,
  "team_id" uuid NOT NULL REFERENCES team(id) ON DELETE CASCADE,
  "position" portable_int32 NOT NULL CHECK (position >= 1),
  "percent" portable_double NOT NULL CHECK (percent >= 0 AND percent <= 100.5),
  "band" portable_int32 NOT NULL CHECK (band >= 0 AND band <= 4),
  "current" portable_bool NOT NULL,
  "reach" portable_string NOT NULL CHECK (reach IN ('', 'impossible', 'reachable', 'undecided')),
  "txid" BIGINT DEFAULT pg_current_xact_id()::text::bigint,
  "scope_id" TEXT GENERATED ALWAYS AS ('public:') STORED NOT NULL
);

CREATE TABLE IF NOT EXISTS game_importance (
  "id" uuid PRIMARY KEY REFERENCES game(id) ON DELETE CASCADE,
  "home" portable_double CHECK (home >= 0),
  "away" portable_double CHECK (away >= 0),
  "txid" BIGINT DEFAULT pg_current_xact_id()::text::bigint,
  "scope_id" TEXT GENERATED ALWAYS AS ('public:') STORED NOT NULL
);

CREATE TABLE IF NOT EXISTS team_rating (
  "id" uuid PRIMARY KEY,
  "team_id" uuid NOT NULL REFERENCES team(id) ON DELETE CASCADE,
  "measure_date" portable_date NOT NULL,
  "offense" portable_double NOT NULL,
  "defense" portable_double NOT NULL,
  "rating" portable_double NOT NULL CHECK (rating >= 0 AND rating <= 100),
  "txid" BIGINT DEFAULT pg_current_xact_id()::text::bigint,
  "scope_id" TEXT GENERATED ALWAYS AS ('public:') STORED NOT NULL
);

CREATE TABLE IF NOT EXISTS team_directory (
  "id" uuid PRIMARY KEY REFERENCES team(id) ON DELETE CASCADE,
  "name" portable_string NOT NULL,
  "city" portable_string,
  "country" portable_string,
  "rating" portable_double,
  "measure_date" portable_date,
  "search_name" portable_string GENERATED ALWAYS AS (name) STORED,
  "search_country" portable_string GENERATED ALWAYS AS (coalesce(country, '')) STORED,
  "rating_display" portable_string GENERATED ALWAYS AS (CASE WHEN rating IS NULL THEN '—' ELSE round(rating::numeric, 2)::text END) STORED,
  "search_key" portable_string GENERATED ALWAYS AS (replace(replace(replace(name, 'ı', 'i'), 'þ', 'th'), 'Þ', 'th')) STORED,
  "country_key" portable_string GENERATED ALWAYS AS (replace(replace(replace(coalesce(country, ''), 'ı', 'i'), 'þ', 'th'), 'Þ', 'th')) STORED,
  "country_id" portable_string DEFAULT '' NOT NULL,
  "region_id" portable_string DEFAULT '' NOT NULL,
  "country_search_key" portable_string DEFAULT '' NOT NULL,
  "region_search_key" portable_string DEFAULT '' NOT NULL,
  "team_type" portable_string DEFAULT 'club' NOT NULL CHECK (team_type IN ('club', 'national')),
  "txid" BIGINT DEFAULT pg_current_xact_id()::text::bigint,
  "scope_id" TEXT GENERATED ALWAYS AS ('public:') STORED NOT NULL
);

CREATE TABLE IF NOT EXISTS team_championship (
  "id" portable_string PRIMARY KEY,
  "team_id" uuid NOT NULL REFERENCES team(id) ON DELETE CASCADE,
  "championship_id" uuid NOT NULL REFERENCES championship(id) ON DELETE CASCADE,
  "championship_name" portable_string NOT NULL,
  "begins" portable_date NOT NULL,
  "ends" portable_date NOT NULL,
  "status" portable_string NOT NULL CHECK (status IN ('current', 'upcoming', 'past')),
  "txid" BIGINT DEFAULT pg_current_xact_id()::text::bigint,
  "scope_id" TEXT GENERATED ALWAYS AS ('public:') STORED NOT NULL
);

CREATE TABLE IF NOT EXISTS team_roster (
  "id" portable_string PRIMARY KEY,
  "team_id" uuid NOT NULL REFERENCES team(id) ON DELETE CASCADE,
  "championship_id" uuid NOT NULL REFERENCES championship(id) ON DELETE CASCADE,
  "player_id" uuid NOT NULL REFERENCES player(id) ON DELETE CASCADE,
  "player_name" portable_string NOT NULL,
  "position" portable_string NOT NULL CHECK (position IN ('', 'g', 'dr', 'dc', 'dl', 'dm', 'cm', 'am', 'fw')),
  "played" portable_int32 NOT NULL CHECK (played >= 0),
  "started" portable_int32 NOT NULL CHECK (started >= 0),
  "came_on" portable_int32 NOT NULL CHECK (came_on >= 0),
  "bench" portable_int32 NOT NULL CHECK (bench >= 0),
  "minutes" portable_int32 NOT NULL CHECK (minutes >= 0),
  "goals" portable_int32 NOT NULL CHECK (goals >= 0),
  "penalties" portable_int32 NOT NULL CHECK (penalties >= 0),
  "own_goals" portable_int32 NOT NULL CHECK (own_goals >= 0),
  "yellow" portable_int32 NOT NULL CHECK (yellow >= 0),
  "red" portable_int32 NOT NULL CHECK (red >= 0),
  "championship_name" portable_string NOT NULL,
  "off_rating" portable_double,
  "def_rating" portable_double,
  "contribution" portable_double,
  "contribution_per90" portable_double,
  "goals_per90" portable_double,
  "search_key" portable_string GENERATED ALWAYS AS (replace(replace(replace(player_name, 'ı', 'i'), 'þ', 'th'), 'Þ', 'th')) STORED,
  "txid" BIGINT DEFAULT pg_current_xact_id()::text::bigint,
  "scope_id" TEXT GENERATED ALWAYS AS ('public:') STORED NOT NULL
);

CREATE TABLE IF NOT EXISTS team_player_history (
  "id" portable_string PRIMARY KEY,
  "team_id" uuid NOT NULL REFERENCES team(id) ON DELETE CASCADE,
  "player_id" uuid NOT NULL REFERENCES player(id) ON DELETE CASCADE,
  "player_name" portable_string NOT NULL,
  "position" portable_string NOT NULL CHECK (position IN ('', 'g', 'dr', 'dc', 'dl', 'dm', 'cm', 'am', 'fw')),
  "country" portable_string,
  "is_current" portable_bool NOT NULL,
  "search_key" portable_string GENERATED ALWAYS AS (replace(replace(replace(player_name, 'ı', 'i'), 'þ', 'th'), 'Þ', 'th')) STORED,
  "txid" BIGINT DEFAULT pg_current_xact_id()::text::bigint,
  "scope_id" TEXT GENERATED ALWAYS AS ('public:') STORED NOT NULL
);

CREATE TABLE IF NOT EXISTS team_group (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "group_id" uuid NOT NULL REFERENCES stage_group(id) ON DELETE CASCADE,
  "team_id" uuid NOT NULL REFERENCES team(id) ON DELETE CASCADE,
  "add_sub" portable_int32 DEFAULT 0 NOT NULL CHECK (add_sub >= -99 AND add_sub <= 99),
  "bias" portable_int32 DEFAULT 0 NOT NULL CHECK (bias >= -99 AND bias <= 99),
  "comment" portable_string CHECK (char_length(comment) <= 500),
  "txid" BIGINT DEFAULT pg_current_xact_id()::text::bigint,
  "scope_id" TEXT GENERATED ALWAYS AS ('public:') STORED NOT NULL
);

CREATE TABLE IF NOT EXISTS geography_region (
  "id" portable_string PRIMARY KEY,
  "name" portable_string NOT NULL,
  "message_key" portable_string NOT NULL,
  "search_key" portable_string NOT NULL,
  "txid" BIGINT DEFAULT pg_current_xact_id()::text::bigint,
  "scope_id" TEXT GENERATED ALWAYS AS ('public:') STORED NOT NULL
);

CREATE TABLE IF NOT EXISTS geography_country (
  "id" portable_string PRIMARY KEY,
  "name" portable_string NOT NULL,
  "region_id" portable_string NOT NULL,
  "message_key" portable_string NOT NULL,
  "aliases" portable_string NOT NULL,
  "search_key" portable_string NOT NULL,
  "region_search_key" portable_string NOT NULL,
  "txid" BIGINT DEFAULT pg_current_xact_id()::text::bigint,
  "scope_id" TEXT GENERATED ALWAYS AS ('public:') STORED NOT NULL
);

CREATE TABLE IF NOT EXISTS player_rating (
  "id" uuid PRIMARY KEY REFERENCES player(id) ON DELETE CASCADE,
  "rating" portable_double NOT NULL,
  "txid" BIGINT DEFAULT pg_current_xact_id()::text::bigint,
  "scope_id" TEXT GENERATED ALWAYS AS ('public:') STORED NOT NULL
);

CREATE TABLE IF NOT EXISTS game_card (
  "id" uuid PRIMARY KEY REFERENCES game(id) ON DELETE CASCADE,
  "phase_id" uuid NOT NULL REFERENCES phase(id) ON DELETE CASCADE,
  "championship_id" uuid NOT NULL REFERENCES championship(id) ON DELETE CASCADE,
  "round" portable_int32 CHECK (round >= 1 AND round <= 99),
  "day" portable_date NOT NULL,
  "kickoff" portable_timestamp,
  "played" portable_bool NOT NULL,
  "home_id" uuid NOT NULL REFERENCES team(id) ON DELETE CASCADE,
  "away_id" uuid NOT NULL REFERENCES team(id) ON DELETE CASCADE,
  "home_name" portable_string NOT NULL,
  "away_name" portable_string NOT NULL,
  "home_score" portable_int32 CHECK (home_score >= 0 AND home_score < 100),
  "away_score" portable_int32 CHECK (away_score >= 0 AND away_score < 100),
  "home_aet" portable_int32 CHECK (home_aet >= 0 AND home_aet < 100),
  "away_aet" portable_int32 CHECK (away_aet >= 0 AND away_aet < 100),
  "home_pen" portable_int32 CHECK (home_pen >= 0 AND home_pen < 100),
  "away_pen" portable_int32 CHECK (away_pen >= 0 AND away_pen < 100),
  "championship_name" portable_string NOT NULL,
  "phase_name" portable_string NOT NULL,
  "stadium_name" portable_string,
  "referee_name" portable_string,
  "attendance" portable_int32 CHECK (attendance >= 0 AND attendance <= 250000),
  "day_display" portable_string GENERATED ALWAYS AS (lpad(extract(day from day)::int::text, 2, '0') || '/' || lpad(extract(month from day)::int::text, 2, '0') || '/' || extract(year from day)::int::text) STORED,
  "kickoff_local" portable_string GENERATED ALWAYS AS (CASE WHEN kickoff IS NULL THEN '' ELSE lpad(extract(hour from (kickoff AT TIME ZONE 'America/Sao_Paulo'))::int::text, 2, '0') || ':' || lpad(extract(minute from (kickoff AT TIME ZONE 'America/Sao_Paulo'))::int::text, 2, '0') END) STORED,
  "stadium_id" uuid REFERENCES stadium(id) ON DELETE CASCADE,
  "referee_id" uuid REFERENCES referee(id) ON DELETE CASCADE,
  "home_upcoming_rank" portable_int32 DEFAULT 0 NOT NULL CHECK (home_upcoming_rank >= 0 AND home_upcoming_rank <= 20),
  "home_recent_rank" portable_int32 DEFAULT 0 NOT NULL CHECK (home_recent_rank >= 0 AND home_recent_rank <= 20),
  "home_upcoming_group" portable_bool DEFAULT false NOT NULL,
  "home_recent_group" portable_bool DEFAULT false NOT NULL,
  "show_country" portable_bool DEFAULT false,
  "home_country" portable_string DEFAULT '',
  "away_country" portable_string DEFAULT '',
  "txid" BIGINT DEFAULT pg_current_xact_id()::text::bigint,
  "scope_id" TEXT GENERATED ALWAYS AS ('public:') STORED NOT NULL
);

CREATE TABLE IF NOT EXISTS team_game (
  "id" portable_string PRIMARY KEY,
  "team_id" uuid NOT NULL REFERENCES team(id) ON DELETE CASCADE,
  "game_id" uuid NOT NULL REFERENCES game(id) ON DELETE CASCADE,
  "side" portable_string NOT NULL CHECK (side IN ('home', 'away')),
  "opponent_id" uuid NOT NULL REFERENCES team(id) ON DELETE CASCADE,
  "opponent_name" portable_string NOT NULL,
  "championship_id" uuid NOT NULL REFERENCES championship(id) ON DELETE CASCADE,
  "championship_name" portable_string NOT NULL,
  "day" portable_date NOT NULL,
  "kickoff" portable_timestamp,
  "played" portable_bool NOT NULL,
  "goals_for" portable_int32 CHECK (goals_for >= 0 AND goals_for < 100),
  "goals_against" portable_int32 CHECK (goals_against >= 0 AND goals_against < 100),
  "result" portable_string NOT NULL CHECK (result IN ('', 'w', 'd', 'l')),
  "day_display" portable_string GENERATED ALWAYS AS (lpad(extract(day from day)::int::text, 2, '0') || '/' || lpad(extract(month from day)::int::text, 2, '0') || '/' || extract(year from day)::int::text) STORED,
  "kickoff_local" portable_string GENERATED ALWAYS AS (CASE WHEN kickoff IS NULL THEN '' ELSE lpad(extract(hour from (kickoff AT TIME ZONE 'America/Sao_Paulo'))::int::text, 2, '0') || ':' || lpad(extract(minute from (kickoff AT TIME ZONE 'America/Sao_Paulo'))::int::text, 2, '0') END) STORED,
  "show_country" portable_bool DEFAULT false,
  "opponent_country" portable_string DEFAULT '',
  "category_id" uuid REFERENCES category(id) ON DELETE CASCADE,
  "phase_key" portable_string NOT NULL,
  "category_key" portable_string NOT NULL,
  "txid" BIGINT DEFAULT pg_current_xact_id()::text::bigint,
  "scope_id" TEXT GENERATED ALWAYS AS ('public:') STORED NOT NULL
);

CREATE TABLE IF NOT EXISTS comment (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "game_id" uuid NOT NULL REFERENCES game(id) ON DELETE CASCADE,
  "app_user_id" uuid DEFAULT auth_uid() NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
  "body" portable_string NOT NULL CHECK (char_length(regexp_replace(body, '^[\s\u0085\u00a0\u1680\u2000-\u200a\u2028\u2029\u202f\u205f\u3000]+|[\s\u0085\u00a0\u1680\u2000-\u200a\u2028\u2029\u202f\u205f\u3000]+$', '', 'g')) > 0 AND char_length(body) <= 1000),
  "created_at" portable_timestamp DEFAULT now() NOT NULL,
  "txid" BIGINT DEFAULT pg_current_xact_id()::text::bigint,
  "scope_id" TEXT GENERATED ALWAYS AS ('public:') STORED NOT NULL
);

CREATE TABLE IF NOT EXISTS player_stat (
  "id" portable_string PRIMARY KEY,
  "championship_id" uuid NOT NULL REFERENCES championship(id) ON DELETE CASCADE,
  "team_id" uuid NOT NULL REFERENCES team(id) ON DELETE CASCADE,
  "player_id" uuid NOT NULL REFERENCES player(id) ON DELETE CASCADE,
  "player_name" portable_string NOT NULL,
  "position" portable_string NOT NULL CHECK (position IN ('', 'g', 'dr', 'dc', 'dl', 'dm', 'cm', 'am', 'fw')),
  "played" portable_int32 NOT NULL CHECK (played >= 0),
  "started" portable_int32 NOT NULL CHECK (started >= 0),
  "came_on" portable_int32 NOT NULL CHECK (came_on >= 0),
  "bench" portable_int32 NOT NULL CHECK (bench >= 0),
  "minutes" portable_int32 NOT NULL CHECK (minutes >= 0),
  "goals" portable_int32 NOT NULL CHECK (goals >= 0),
  "penalties" portable_int32 NOT NULL CHECK (penalties >= 0),
  "own_goals" portable_int32 NOT NULL CHECK (own_goals >= 0),
  "yellow" portable_int32 NOT NULL CHECK (yellow >= 0),
  "red" portable_int32 NOT NULL CHECK (red >= 0),
  "championship_name" portable_string NOT NULL,
  "team_name" portable_string NOT NULL,
  "off_rating" portable_double,
  "def_rating" portable_double,
  "contribution" portable_double,
  "contribution_per90" portable_double,
  "goals_per90" portable_double,
  "txid" BIGINT DEFAULT pg_current_xact_id()::text::bigint,
  "scope_id" TEXT GENERATED ALWAYS AS ('public:') STORED NOT NULL
);

CREATE TABLE IF NOT EXISTS phase_round (
  "id" portable_string PRIMARY KEY,
  "phase_id" uuid NOT NULL REFERENCES phase(id) ON DELETE CASCADE,
  "current" portable_int32 NOT NULL CHECK (current >= 1),
  "next" portable_int32 CHECK (next >= 1),
  "txid" BIGINT DEFAULT pg_current_xact_id()::text::bigint,
  "scope_id" TEXT GENERATED ALWAYS AS ('public:') STORED NOT NULL
);

CREATE TABLE IF NOT EXISTS team_comment (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "team_id" uuid NOT NULL REFERENCES team(id) ON DELETE CASCADE,
  "app_user_id" uuid DEFAULT auth_uid() NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
  "body" portable_string NOT NULL CHECK (char_length(regexp_replace(body, '^[\s\u0085\u00a0\u1680\u2000-\u200a\u2028\u2029\u202f\u205f\u3000]+|[\s\u0085\u00a0\u1680\u2000-\u200a\u2028\u2029\u202f\u205f\u3000]+$', '', 'g')) > 0 AND char_length(body) <= 1000),
  "created_at" portable_timestamp DEFAULT now() NOT NULL,
  "txid" BIGINT DEFAULT pg_current_xact_id()::text::bigint,
  "scope_id" TEXT GENERATED ALWAYS AS ('public:') STORED NOT NULL
);

CREATE TABLE IF NOT EXISTS team_campaign_point (
  "id" portable_string PRIMARY KEY,
  "group_id" uuid NOT NULL REFERENCES stage_group(id) ON DELETE CASCADE,
  "team_id" uuid NOT NULL REFERENCES team(id) ON DELETE CASCADE,
  "game_id" uuid NOT NULL REFERENCES game(id) ON DELETE CASCADE,
  "sequence" portable_int32 NOT NULL CHECK (sequence >= 1),
  "day" portable_date NOT NULL,
  "points" portable_int32 NOT NULL,
  "position" portable_int32 NOT NULL CHECK (position >= 1),
  "result" portable_string NOT NULL CHECK (result IN ('w', 'd', 'l')),
  "txid" BIGINT DEFAULT pg_current_xact_id()::text::bigint,
  "scope_id" TEXT GENERATED ALWAYS AS ('public:') STORED NOT NULL
);

CREATE TABLE IF NOT EXISTS team_odds_history (
  "id" portable_string PRIMARY KEY,
  "group_id" uuid NOT NULL REFERENCES stage_group(id) ON DELETE CASCADE,
  "team_id" uuid NOT NULL REFERENCES team(id) ON DELETE CASCADE,
  "recorded_on" portable_date NOT NULL,
  "captured_at" portable_timestamp,
  "position" portable_int32 NOT NULL CHECK (position >= 1),
  "percent" portable_double NOT NULL CHECK (percent >= 0 AND percent <= 100),
  "source" portable_string NOT NULL CHECK (source IN ('imported', 'computed')),
  "txid" BIGINT DEFAULT pg_current_xact_id()::text::bigint,
  "scope_id" TEXT GENERATED ALWAYS AS ('public:') STORED NOT NULL
);

CREATE TABLE IF NOT EXISTS team_rating_chart (
  "id" portable_string PRIMARY KEY,
  "team_id" uuid NOT NULL REFERENCES team(id) ON DELETE CASCADE,
  "period" portable_string NOT NULL CHECK (period IN ('1m', '3m', '6m', '1y', '5y', 'all')),
  "series_json" portable_string NOT NULL,
  "txid" BIGINT DEFAULT pg_current_xact_id()::text::bigint,
  "scope_id" TEXT GENERATED ALWAYS AS ('public:') STORED NOT NULL
);

CREATE TABLE IF NOT EXISTS team_odds_chart (
  "id" portable_string PRIMARY KEY,
  "group_id" uuid NOT NULL REFERENCES stage_group(id) ON DELETE CASCADE,
  "team_id" uuid NOT NULL REFERENCES team(id) ON DELETE CASCADE,
  "zone_id" uuid NOT NULL REFERENCES zone(id) ON DELETE CASCADE,
  "series_json" portable_string NOT NULL,
  "txid" BIGINT DEFAULT pg_current_xact_id()::text::bigint,
  "scope_id" TEXT GENERATED ALWAYS AS ('public:') STORED NOT NULL
);

CREATE TABLE IF NOT EXISTS team_roster_total (
  "id" portable_string PRIMARY KEY,
  "team_id" uuid NOT NULL REFERENCES team(id) ON DELETE CASCADE,
  "championship_id" uuid NOT NULL REFERENCES championship(id) ON DELETE CASCADE,
  "championship_name" portable_string NOT NULL,
  "played" portable_int32 NOT NULL CHECK (played >= 0),
  "started" portable_int32 NOT NULL CHECK (started >= 0),
  "came_on" portable_int32 NOT NULL CHECK (came_on >= 0),
  "bench" portable_int32 NOT NULL CHECK (bench >= 0),
  "minutes" portable_int32 NOT NULL CHECK (minutes >= 0),
  "goals" portable_int32 NOT NULL CHECK (goals >= 0),
  "penalties" portable_int32 NOT NULL CHECK (penalties >= 0),
  "own_goals" portable_int32 NOT NULL CHECK (own_goals >= 0),
  "yellow" portable_int32 NOT NULL CHECK (yellow >= 0),
  "red" portable_int32 NOT NULL CHECK (red >= 0),
  "off_rating" portable_double,
  "def_rating" portable_double,
  "contribution" portable_double,
  "contribution_per90" portable_double,
  "goals_per90" portable_double,
  "txid" BIGINT DEFAULT pg_current_xact_id()::text::bigint,
  "scope_id" TEXT GENERATED ALWAYS AS ('public:') STORED NOT NULL
);

CREATE TABLE IF NOT EXISTS home_championship (
  "id" uuid PRIMARY KEY REFERENCES championship(id) ON DELETE CASCADE,
  "region" portable_string NOT NULL,
  "region_name" portable_string NOT NULL,
  "full_name" portable_string NOT NULL,
  "strength" portable_double NOT NULL,
  "txid" BIGINT DEFAULT pg_current_xact_id()::text::bigint,
  "scope_id" TEXT GENERATED ALWAYS AS ('public:') STORED NOT NULL
);

CREATE TABLE IF NOT EXISTS team_player (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "championship_id" uuid NOT NULL REFERENCES championship(id) ON DELETE CASCADE,
  "team_id" uuid NOT NULL REFERENCES team(id) ON DELETE CASCADE,
  "player_id" uuid NOT NULL REFERENCES player(id) ON DELETE CASCADE,
  "txid" BIGINT DEFAULT pg_current_xact_id()::text::bigint,
  "scope_id" TEXT GENERATED ALWAYS AS ('public:') STORED NOT NULL
);

CREATE TABLE IF NOT EXISTS rating_eval (
  "id" uuid PRIMARY KEY REFERENCES phase(id) ON DELETE CASCADE,
  "rps" portable_double NOT NULL CHECK (rps >= 0),
  "txid" BIGINT DEFAULT pg_current_xact_id()::text::bigint,
  "scope_id" TEXT GENERATED ALWAYS AS ('public:') STORED NOT NULL
);

CREATE TABLE IF NOT EXISTS home_game_card (
  "id" uuid PRIMARY KEY REFERENCES game(id) ON DELETE CASCADE,
  "phase_id" uuid NOT NULL REFERENCES phase(id) ON DELETE CASCADE,
  "championship_id" uuid NOT NULL REFERENCES championship(id) ON DELETE CASCADE,
  "round" portable_int32 CHECK (round >= 1 AND round <= 99),
  "day" portable_date NOT NULL,
  "kickoff" portable_timestamp,
  "played" portable_bool NOT NULL,
  "home_id" uuid NOT NULL REFERENCES team(id) ON DELETE CASCADE,
  "away_id" uuid NOT NULL REFERENCES team(id) ON DELETE CASCADE,
  "home_name" portable_string NOT NULL,
  "away_name" portable_string NOT NULL,
  "home_score" portable_int32 CHECK (home_score >= 0 AND home_score < 100),
  "away_score" portable_int32 CHECK (away_score >= 0 AND away_score < 100),
  "home_aet" portable_int32 CHECK (home_aet >= 0 AND home_aet < 100),
  "away_aet" portable_int32 CHECK (away_aet >= 0 AND away_aet < 100),
  "home_pen" portable_int32 CHECK (home_pen >= 0 AND home_pen < 100),
  "away_pen" portable_int32 CHECK (away_pen >= 0 AND away_pen < 100),
  "championship_name" portable_string NOT NULL,
  "phase_name" portable_string NOT NULL,
  "stadium_name" portable_string,
  "referee_name" portable_string,
  "attendance" portable_int32 CHECK (attendance >= 0 AND attendance <= 250000),
  "day_display" portable_string GENERATED ALWAYS AS (lpad(extract(day from day)::int::text, 2, '0') || '/' || lpad(extract(month from day)::int::text, 2, '0') || '/' || extract(year from day)::int::text) STORED,
  "kickoff_local" portable_string GENERATED ALWAYS AS (CASE WHEN kickoff IS NULL THEN '' ELSE lpad(extract(hour from (kickoff AT TIME ZONE 'America/Sao_Paulo'))::int::text, 2, '0') || ':' || lpad(extract(minute from (kickoff AT TIME ZONE 'America/Sao_Paulo'))::int::text, 2, '0') END) STORED,
  "stadium_id" uuid REFERENCES stadium(id) ON DELETE CASCADE,
  "referee_id" uuid REFERENCES referee(id) ON DELETE CASCADE,
  "home_upcoming_rank" portable_int32 DEFAULT 0 NOT NULL CHECK (home_upcoming_rank >= 0 AND home_upcoming_rank <= 20),
  "home_recent_rank" portable_int32 DEFAULT 0 NOT NULL CHECK (home_recent_rank >= 0 AND home_recent_rank <= 20),
  "home_upcoming_group" portable_bool DEFAULT false NOT NULL,
  "home_recent_group" portable_bool DEFAULT false NOT NULL,
  "show_country" portable_bool DEFAULT false,
  "home_country" portable_string DEFAULT '',
  "away_country" portable_string DEFAULT '',
  "home_highlighted" portable_bool DEFAULT false NOT NULL,
  "txid" BIGINT DEFAULT pg_current_xact_id()::text::bigint,
  "scope_id" TEXT GENERATED ALWAYS AS ('public:') STORED NOT NULL
);

CREATE TABLE IF NOT EXISTS matches_game_card (
  "id" uuid PRIMARY KEY REFERENCES game(id) ON DELETE CASCADE,
  "phase_id" uuid NOT NULL REFERENCES phase(id) ON DELETE CASCADE,
  "championship_id" uuid NOT NULL REFERENCES championship(id) ON DELETE CASCADE,
  "round" portable_int32 CHECK (round >= 1 AND round <= 99),
  "day" portable_date NOT NULL,
  "kickoff" portable_timestamp,
  "played" portable_bool NOT NULL,
  "home_id" uuid NOT NULL REFERENCES team(id) ON DELETE CASCADE,
  "away_id" uuid NOT NULL REFERENCES team(id) ON DELETE CASCADE,
  "home_name" portable_string NOT NULL,
  "away_name" portable_string NOT NULL,
  "home_score" portable_int32 CHECK (home_score >= 0 AND home_score < 100),
  "away_score" portable_int32 CHECK (away_score >= 0 AND away_score < 100),
  "home_aet" portable_int32 CHECK (home_aet >= 0 AND home_aet < 100),
  "away_aet" portable_int32 CHECK (away_aet >= 0 AND away_aet < 100),
  "home_pen" portable_int32 CHECK (home_pen >= 0 AND home_pen < 100),
  "away_pen" portable_int32 CHECK (away_pen >= 0 AND away_pen < 100),
  "championship_name" portable_string NOT NULL,
  "phase_name" portable_string NOT NULL,
  "stadium_name" portable_string,
  "referee_name" portable_string,
  "attendance" portable_int32 CHECK (attendance >= 0 AND attendance <= 250000),
  "day_display" portable_string GENERATED ALWAYS AS (lpad(extract(day from day)::int::text, 2, '0') || '/' || lpad(extract(month from day)::int::text, 2, '0') || '/' || extract(year from day)::int::text) STORED,
  "kickoff_local" portable_string GENERATED ALWAYS AS (CASE WHEN kickoff IS NULL THEN '' ELSE lpad(extract(hour from (kickoff AT TIME ZONE 'America/Sao_Paulo'))::int::text, 2, '0') || ':' || lpad(extract(minute from (kickoff AT TIME ZONE 'America/Sao_Paulo'))::int::text, 2, '0') END) STORED,
  "stadium_id" uuid REFERENCES stadium(id) ON DELETE CASCADE,
  "referee_id" uuid REFERENCES referee(id) ON DELETE CASCADE,
  "home_upcoming_rank" portable_int32 DEFAULT 0 NOT NULL CHECK (home_upcoming_rank >= 0 AND home_upcoming_rank <= 20),
  "home_recent_rank" portable_int32 DEFAULT 0 NOT NULL CHECK (home_recent_rank >= 0 AND home_recent_rank <= 20),
  "home_upcoming_group" portable_bool DEFAULT false NOT NULL,
  "home_recent_group" portable_bool DEFAULT false NOT NULL,
  "show_country" portable_bool DEFAULT false,
  "home_country" portable_string DEFAULT '',
  "away_country" portable_string DEFAULT '',
  "txid" BIGINT DEFAULT pg_current_xact_id()::text::bigint,
  "scope_id" TEXT GENERATED ALWAYS AS ('public:') STORED NOT NULL
);

CREATE TABLE IF NOT EXISTS editor (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "app_user_id" uuid NOT NULL UNIQUE REFERENCES app_user(id) ON DELETE CASCADE,
  "txid" BIGINT DEFAULT pg_current_xact_id()::text::bigint,
  "scope_id" TEXT GENERATED ALWAYS AS ('user:' || "app_user_id") STORED NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_championship_begins ON championship USING btree (begins);
CREATE INDEX IF NOT EXISTS idx_phase_championship_id ON phase USING btree (championship_id);
CREATE INDEX IF NOT EXISTS idx_stage_group_phase_id ON stage_group USING btree (phase_id);
CREATE INDEX IF NOT EXISTS idx_zone_group_id ON zone USING btree (group_id);
CREATE INDEX IF NOT EXISTS idx_team_name ON team USING btree (name);
CREATE INDEX IF NOT EXISTS idx_player_name ON player USING btree (name);
CREATE INDEX IF NOT EXISTS idx_game_phase_id ON game USING btree (phase_id);
CREATE INDEX IF NOT EXISTS idx_game_home_id ON game USING btree (home_id);
CREATE INDEX IF NOT EXISTS idx_game_away_id ON game USING btree (away_id);
CREATE INDEX IF NOT EXISTS idx_game_day ON game USING btree (day);
CREATE INDEX IF NOT EXISTS idx_game_referee_id ON game USING btree (referee_id);
CREATE INDEX IF NOT EXISTS idx_game_stadium_id ON game USING btree (stadium_id);
CREATE INDEX IF NOT EXISTS idx_goal_game_id ON goal USING btree (game_id);
CREATE INDEX IF NOT EXISTS idx_goal_player_id ON goal USING btree (player_id);
CREATE INDEX IF NOT EXISTS idx_player_game_player_id ON player_game USING btree (player_id);
CREATE INDEX IF NOT EXISTS idx_player_game_game_id ON player_game USING btree (game_id);
CREATE INDEX IF NOT EXISTS idx_standing_group_id ON standing USING btree (group_id);
CREATE INDEX IF NOT EXISTS idx_team_chance_group_id ON team_chance USING btree (group_id);
CREATE INDEX IF NOT EXISTS idx_zone_chance_group_id ON zone_chance USING btree (group_id);
CREATE INDEX IF NOT EXISTS idx_position_chance_group_id ON position_chance USING btree (group_id);
CREATE INDEX IF NOT EXISTS idx_team_rating_team_id ON team_rating USING btree (team_id);
CREATE INDEX IF NOT EXISTS idx_team_championship_team_id ON team_championship USING btree (team_id);
CREATE INDEX IF NOT EXISTS idx_team_roster_team_id ON team_roster USING btree (team_id);
CREATE INDEX IF NOT EXISTS idx_team_player_history_team_id ON team_player_history USING btree (team_id);
CREATE INDEX IF NOT EXISTS idx_team_group_team_id ON team_group USING btree (team_id);
CREATE INDEX IF NOT EXISTS idx_game_card_phase_id ON game_card USING btree (phase_id);
CREATE INDEX IF NOT EXISTS idx_game_card_day ON game_card USING btree (day);
CREATE INDEX IF NOT EXISTS idx_game_card_stadium_id ON game_card USING btree (stadium_id);
CREATE INDEX IF NOT EXISTS idx_game_card_referee_id ON game_card USING btree (referee_id);
CREATE INDEX IF NOT EXISTS idx_team_game_team_id ON team_game USING btree (team_id);
CREATE INDEX IF NOT EXISTS idx_team_game_game_id ON team_game USING btree (game_id);
CREATE INDEX IF NOT EXISTS idx_comment_game_id ON comment USING btree (game_id);
CREATE INDEX IF NOT EXISTS idx_player_stat_player_id ON player_stat USING btree (player_id);
CREATE INDEX IF NOT EXISTS idx_player_stat_team_id ON player_stat USING btree (team_id);
CREATE INDEX IF NOT EXISTS idx_team_comment_team_id ON team_comment USING btree (team_id);
CREATE INDEX IF NOT EXISTS idx_team_campaign_point_group_id ON team_campaign_point USING btree (group_id);
CREATE INDEX IF NOT EXISTS idx_team_campaign_point_team_id ON team_campaign_point USING btree (team_id);
CREATE INDEX IF NOT EXISTS idx_team_odds_history_group_id ON team_odds_history USING btree (group_id);
CREATE INDEX IF NOT EXISTS idx_team_odds_history_team_id ON team_odds_history USING btree (team_id);
CREATE INDEX IF NOT EXISTS idx_team_rating_chart_team_id ON team_rating_chart USING btree (team_id);
CREATE INDEX IF NOT EXISTS idx_team_odds_chart_group_id ON team_odds_chart USING btree (group_id);
CREATE INDEX IF NOT EXISTS idx_team_odds_chart_team_id ON team_odds_chart USING btree (team_id);
CREATE INDEX IF NOT EXISTS idx_team_roster_total_team_id ON team_roster_total USING btree (team_id);
CREATE INDEX IF NOT EXISTS idx_team_player_player_id ON team_player USING btree (player_id);
CREATE INDEX IF NOT EXISTS idx_team_player_team_id ON team_player USING btree (team_id);
CREATE INDEX IF NOT EXISTS idx_home_game_card_championship_id ON home_game_card USING btree (championship_id);
CREATE INDEX IF NOT EXISTS idx_matches_game_card_championship_id ON matches_game_card USING btree (championship_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_player_game ON player_game (game_id, player_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_team_group ON team_group (group_id, team_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_team_player ON team_player (championship_id, team_id, player_id);

COMMIT;
