-- generated by pronto from program.cue — do not edit
SET lock_timeout = '5s';
SET statement_timeout = '60s';

BEGIN;

CALL rls_protect('app_user');
ALTER TABLE app_user ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS app_user_app_user_select ON app_user;
CREATE POLICY app_user_app_user_select ON app_user FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS app_user_service_all ON app_user;
CREATE POLICY app_user_service_all ON app_user FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('category');
ALTER TABLE category ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS category_app_user_select ON category;
CREATE POLICY category_app_user_select ON category FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS category_service_all ON category;
CREATE POLICY category_service_all ON category FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('championship');
ALTER TABLE championship ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS championship_app_user_select ON championship;
CREATE POLICY championship_app_user_select ON championship FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS championship_service_all ON championship;
CREATE POLICY championship_service_all ON championship FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('phase');
ALTER TABLE phase ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS phase_app_user_select ON phase;
CREATE POLICY phase_app_user_select ON phase FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS phase_service_all ON phase;
CREATE POLICY phase_service_all ON phase FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('stage_group');
ALTER TABLE stage_group ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS stage_group_app_user_select ON stage_group;
CREATE POLICY stage_group_app_user_select ON stage_group FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS stage_group_service_all ON stage_group;
CREATE POLICY stage_group_service_all ON stage_group FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('zone');
ALTER TABLE zone ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS zone_app_user_select ON zone;
CREATE POLICY zone_app_user_select ON zone FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS zone_service_all ON zone;
CREATE POLICY zone_service_all ON zone FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('stadium');
ALTER TABLE stadium ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS stadium_app_user_select ON stadium;
CREATE POLICY stadium_app_user_select ON stadium FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS stadium_service_all ON stadium;
CREATE POLICY stadium_service_all ON stadium FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('team');
ALTER TABLE team ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS team_app_user_select ON team;
CREATE POLICY team_app_user_select ON team FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS team_service_all ON team;
CREATE POLICY team_service_all ON team FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('team_group');
ALTER TABLE team_group ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS team_group_app_user_select ON team_group;
CREATE POLICY team_group_app_user_select ON team_group FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS team_group_service_all ON team_group;
CREATE POLICY team_group_service_all ON team_group FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('referee');
ALTER TABLE referee ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS referee_app_user_select ON referee;
CREATE POLICY referee_app_user_select ON referee FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS referee_service_all ON referee;
CREATE POLICY referee_service_all ON referee FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('player');
ALTER TABLE player ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS player_app_user_select ON player;
CREATE POLICY player_app_user_select ON player FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS player_service_all ON player;
CREATE POLICY player_service_all ON player FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('team_player');
ALTER TABLE team_player ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS team_player_app_user_select ON team_player;
CREATE POLICY team_player_app_user_select ON team_player FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS team_player_service_all ON team_player;
CREATE POLICY team_player_service_all ON team_player FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('game');
ALTER TABLE game ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS game_app_user_select ON game;
CREATE POLICY game_app_user_select ON game FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS game_service_all ON game;
CREATE POLICY game_service_all ON game FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('goal');
ALTER TABLE goal ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS goal_app_user_select ON goal;
CREATE POLICY goal_app_user_select ON goal FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS goal_service_all ON goal;
CREATE POLICY goal_service_all ON goal FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('player_game');
ALTER TABLE player_game ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS player_game_app_user_select ON player_game;
CREATE POLICY player_game_app_user_select ON player_game FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS player_game_service_all ON player_game;
CREATE POLICY player_game_service_all ON player_game FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('standing');
ALTER TABLE standing ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS standing_app_user_select ON standing;
CREATE POLICY standing_app_user_select ON standing FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS standing_service_all ON standing;
CREATE POLICY standing_service_all ON standing FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('team_chance');
ALTER TABLE team_chance ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS team_chance_app_user_select ON team_chance;
CREATE POLICY team_chance_app_user_select ON team_chance FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS team_chance_service_all ON team_chance;
CREATE POLICY team_chance_service_all ON team_chance FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('zone_chance');
ALTER TABLE zone_chance ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS zone_chance_app_user_select ON zone_chance;
CREATE POLICY zone_chance_app_user_select ON zone_chance FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS zone_chance_service_all ON zone_chance;
CREATE POLICY zone_chance_service_all ON zone_chance FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('position_chance');
ALTER TABLE position_chance ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS position_chance_app_user_select ON position_chance;
CREATE POLICY position_chance_app_user_select ON position_chance FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS position_chance_service_all ON position_chance;
CREATE POLICY position_chance_service_all ON position_chance FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('game_importance');
ALTER TABLE game_importance ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS game_importance_app_user_select ON game_importance;
CREATE POLICY game_importance_app_user_select ON game_importance FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS game_importance_service_all ON game_importance;
CREATE POLICY game_importance_service_all ON game_importance FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('team_rating');
ALTER TABLE team_rating ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS team_rating_app_user_select ON team_rating;
CREATE POLICY team_rating_app_user_select ON team_rating FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS team_rating_service_all ON team_rating;
CREATE POLICY team_rating_service_all ON team_rating FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('player_rating');
ALTER TABLE player_rating ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS player_rating_app_user_select ON player_rating;
CREATE POLICY player_rating_app_user_select ON player_rating FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS player_rating_service_all ON player_rating;
CREATE POLICY player_rating_service_all ON player_rating FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('rating_eval');
ALTER TABLE rating_eval ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rating_eval_app_user_select ON rating_eval;
CREATE POLICY rating_eval_app_user_select ON rating_eval FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS rating_eval_service_all ON rating_eval;
CREATE POLICY rating_eval_service_all ON rating_eval FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('game_card');
ALTER TABLE game_card ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS game_card_app_user_select ON game_card;
CREATE POLICY game_card_app_user_select ON game_card FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS game_card_service_all ON game_card;
CREATE POLICY game_card_service_all ON game_card FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('home_game_card');
ALTER TABLE home_game_card ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS home_game_card_app_user_select ON home_game_card;
CREATE POLICY home_game_card_app_user_select ON home_game_card FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS home_game_card_service_all ON home_game_card;
CREATE POLICY home_game_card_service_all ON home_game_card FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('team_game');
ALTER TABLE team_game ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS team_game_app_user_select ON team_game;
CREATE POLICY team_game_app_user_select ON team_game FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS team_game_service_all ON team_game;
CREATE POLICY team_game_service_all ON team_game FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('comment');
ALTER TABLE comment ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS comment_app_user_select ON comment;
CREATE POLICY comment_app_user_select ON comment FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS comment_service_all ON comment;
CREATE POLICY comment_service_all ON comment FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('editor');
ALTER TABLE editor ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS editor_app_user_select ON editor;
CREATE POLICY editor_app_user_select ON editor FOR SELECT TO app_user USING (editor.app_user_id = auth_uid());
DROP POLICY IF EXISTS editor_app_user_insert ON editor;
CREATE POLICY editor_app_user_insert ON editor FOR INSERT TO app_user WITH CHECK (editor.app_user_id = auth_uid());
DROP POLICY IF EXISTS editor_app_user_update ON editor;
CREATE POLICY editor_app_user_update ON editor FOR UPDATE TO app_user USING (editor.app_user_id = auth_uid());
DROP POLICY IF EXISTS editor_app_user_delete ON editor;
CREATE POLICY editor_app_user_delete ON editor FOR DELETE TO app_user USING (editor.app_user_id = auth_uid());
DROP POLICY IF EXISTS editor_service_all ON editor;
CREATE POLICY editor_service_all ON editor FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('player_stat');
ALTER TABLE player_stat ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS player_stat_app_user_select ON player_stat;
CREATE POLICY player_stat_app_user_select ON player_stat FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS player_stat_service_all ON player_stat;
CREATE POLICY player_stat_service_all ON player_stat FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('phase_round');
ALTER TABLE phase_round ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS phase_round_app_user_select ON phase_round;
CREATE POLICY phase_round_app_user_select ON phase_round FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS phase_round_service_all ON phase_round;
CREATE POLICY phase_round_service_all ON phase_round FOR ALL TO service USING (true) WITH CHECK (true);

COMMIT;
