-- generated by pronto from program.cue — do not edit
SET lock_timeout = '5s';
SET statement_timeout = '60s';

BEGIN;

CREATE OR REPLACE FUNCTION restamp_txid() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  NEW.txid := pg_current_xact_id()::text::bigint;
  RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS restamp_txid ON app_user;
CREATE TRIGGER restamp_txid BEFORE UPDATE ON app_user
  FOR EACH ROW EXECUTE FUNCTION restamp_txid();
DROP TRIGGER IF EXISTS restamp_txid ON category;
CREATE TRIGGER restamp_txid BEFORE UPDATE ON category
  FOR EACH ROW EXECUTE FUNCTION restamp_txid();
DROP TRIGGER IF EXISTS restamp_txid ON championship;
CREATE TRIGGER restamp_txid BEFORE UPDATE ON championship
  FOR EACH ROW EXECUTE FUNCTION restamp_txid();
DROP TRIGGER IF EXISTS restamp_txid ON phase;
CREATE TRIGGER restamp_txid BEFORE UPDATE ON phase
  FOR EACH ROW EXECUTE FUNCTION restamp_txid();
DROP TRIGGER IF EXISTS restamp_txid ON stage_group;
CREATE TRIGGER restamp_txid BEFORE UPDATE ON stage_group
  FOR EACH ROW EXECUTE FUNCTION restamp_txid();
DROP TRIGGER IF EXISTS restamp_txid ON zone;
CREATE TRIGGER restamp_txid BEFORE UPDATE ON zone
  FOR EACH ROW EXECUTE FUNCTION restamp_txid();
DROP TRIGGER IF EXISTS restamp_txid ON stadium;
CREATE TRIGGER restamp_txid BEFORE UPDATE ON stadium
  FOR EACH ROW EXECUTE FUNCTION restamp_txid();
DROP TRIGGER IF EXISTS restamp_txid ON team;
CREATE TRIGGER restamp_txid BEFORE UPDATE ON team
  FOR EACH ROW EXECUTE FUNCTION restamp_txid();
DROP TRIGGER IF EXISTS restamp_txid ON referee;
CREATE TRIGGER restamp_txid BEFORE UPDATE ON referee
  FOR EACH ROW EXECUTE FUNCTION restamp_txid();
DROP TRIGGER IF EXISTS restamp_txid ON player;
CREATE TRIGGER restamp_txid BEFORE UPDATE ON player
  FOR EACH ROW EXECUTE FUNCTION restamp_txid();
DROP TRIGGER IF EXISTS restamp_txid ON game;
CREATE TRIGGER restamp_txid BEFORE UPDATE ON game
  FOR EACH ROW EXECUTE FUNCTION restamp_txid();
DROP TRIGGER IF EXISTS restamp_txid ON goal;
CREATE TRIGGER restamp_txid BEFORE UPDATE ON goal
  FOR EACH ROW EXECUTE FUNCTION restamp_txid();
DROP TRIGGER IF EXISTS restamp_txid ON player_game;
CREATE TRIGGER restamp_txid BEFORE UPDATE ON player_game
  FOR EACH ROW EXECUTE FUNCTION restamp_txid();
DROP TRIGGER IF EXISTS restamp_txid ON standing;
CREATE TRIGGER restamp_txid BEFORE UPDATE ON standing
  FOR EACH ROW EXECUTE FUNCTION restamp_txid();
DROP TRIGGER IF EXISTS restamp_txid ON team_chance;
CREATE TRIGGER restamp_txid BEFORE UPDATE ON team_chance
  FOR EACH ROW EXECUTE FUNCTION restamp_txid();
DROP TRIGGER IF EXISTS restamp_txid ON zone_chance;
CREATE TRIGGER restamp_txid BEFORE UPDATE ON zone_chance
  FOR EACH ROW EXECUTE FUNCTION restamp_txid();
DROP TRIGGER IF EXISTS restamp_txid ON position_chance;
CREATE TRIGGER restamp_txid BEFORE UPDATE ON position_chance
  FOR EACH ROW EXECUTE FUNCTION restamp_txid();
DROP TRIGGER IF EXISTS restamp_txid ON game_importance;
CREATE TRIGGER restamp_txid BEFORE UPDATE ON game_importance
  FOR EACH ROW EXECUTE FUNCTION restamp_txid();
DROP TRIGGER IF EXISTS restamp_txid ON team_rating;
CREATE TRIGGER restamp_txid BEFORE UPDATE ON team_rating
  FOR EACH ROW EXECUTE FUNCTION restamp_txid();
DROP TRIGGER IF EXISTS restamp_txid ON team_directory;
CREATE TRIGGER restamp_txid BEFORE UPDATE ON team_directory
  FOR EACH ROW EXECUTE FUNCTION restamp_txid();
DROP TRIGGER IF EXISTS restamp_txid ON team_championship;
CREATE TRIGGER restamp_txid BEFORE UPDATE ON team_championship
  FOR EACH ROW EXECUTE FUNCTION restamp_txid();
DROP TRIGGER IF EXISTS restamp_txid ON team_roster;
CREATE TRIGGER restamp_txid BEFORE UPDATE ON team_roster
  FOR EACH ROW EXECUTE FUNCTION restamp_txid();
DROP TRIGGER IF EXISTS restamp_txid ON team_player_history;
CREATE TRIGGER restamp_txid BEFORE UPDATE ON team_player_history
  FOR EACH ROW EXECUTE FUNCTION restamp_txid();
DROP TRIGGER IF EXISTS restamp_txid ON team_group;
CREATE TRIGGER restamp_txid BEFORE UPDATE ON team_group
  FOR EACH ROW EXECUTE FUNCTION restamp_txid();
DROP TRIGGER IF EXISTS restamp_txid ON geography_region;
CREATE TRIGGER restamp_txid BEFORE UPDATE ON geography_region
  FOR EACH ROW EXECUTE FUNCTION restamp_txid();
DROP TRIGGER IF EXISTS restamp_txid ON geography_country;
CREATE TRIGGER restamp_txid BEFORE UPDATE ON geography_country
  FOR EACH ROW EXECUTE FUNCTION restamp_txid();
DROP TRIGGER IF EXISTS restamp_txid ON player_rating;
CREATE TRIGGER restamp_txid BEFORE UPDATE ON player_rating
  FOR EACH ROW EXECUTE FUNCTION restamp_txid();
DROP TRIGGER IF EXISTS restamp_txid ON game_card;
CREATE TRIGGER restamp_txid BEFORE UPDATE ON game_card
  FOR EACH ROW EXECUTE FUNCTION restamp_txid();
DROP TRIGGER IF EXISTS restamp_txid ON team_game;
CREATE TRIGGER restamp_txid BEFORE UPDATE ON team_game
  FOR EACH ROW EXECUTE FUNCTION restamp_txid();
DROP TRIGGER IF EXISTS restamp_txid ON comment;
CREATE TRIGGER restamp_txid BEFORE UPDATE ON comment
  FOR EACH ROW EXECUTE FUNCTION restamp_txid();
DROP TRIGGER IF EXISTS restamp_txid ON player_stat;
CREATE TRIGGER restamp_txid BEFORE UPDATE ON player_stat
  FOR EACH ROW EXECUTE FUNCTION restamp_txid();
DROP TRIGGER IF EXISTS restamp_txid ON phase_round;
CREATE TRIGGER restamp_txid BEFORE UPDATE ON phase_round
  FOR EACH ROW EXECUTE FUNCTION restamp_txid();
DROP TRIGGER IF EXISTS restamp_txid ON team_comment;
CREATE TRIGGER restamp_txid BEFORE UPDATE ON team_comment
  FOR EACH ROW EXECUTE FUNCTION restamp_txid();
DROP TRIGGER IF EXISTS restamp_txid ON team_campaign_point;
CREATE TRIGGER restamp_txid BEFORE UPDATE ON team_campaign_point
  FOR EACH ROW EXECUTE FUNCTION restamp_txid();
DROP TRIGGER IF EXISTS restamp_txid ON team_odds_history;
CREATE TRIGGER restamp_txid BEFORE UPDATE ON team_odds_history
  FOR EACH ROW EXECUTE FUNCTION restamp_txid();
DROP TRIGGER IF EXISTS restamp_txid ON team_rating_chart;
CREATE TRIGGER restamp_txid BEFORE UPDATE ON team_rating_chart
  FOR EACH ROW EXECUTE FUNCTION restamp_txid();
DROP TRIGGER IF EXISTS restamp_txid ON team_odds_chart;
CREATE TRIGGER restamp_txid BEFORE UPDATE ON team_odds_chart
  FOR EACH ROW EXECUTE FUNCTION restamp_txid();
DROP TRIGGER IF EXISTS restamp_txid ON team_roster_total;
CREATE TRIGGER restamp_txid BEFORE UPDATE ON team_roster_total
  FOR EACH ROW EXECUTE FUNCTION restamp_txid();
DROP TRIGGER IF EXISTS restamp_txid ON home_championship;
CREATE TRIGGER restamp_txid BEFORE UPDATE ON home_championship
  FOR EACH ROW EXECUTE FUNCTION restamp_txid();
DROP TRIGGER IF EXISTS restamp_txid ON team_player;
CREATE TRIGGER restamp_txid BEFORE UPDATE ON team_player
  FOR EACH ROW EXECUTE FUNCTION restamp_txid();
DROP TRIGGER IF EXISTS restamp_txid ON rating_eval;
CREATE TRIGGER restamp_txid BEFORE UPDATE ON rating_eval
  FOR EACH ROW EXECUTE FUNCTION restamp_txid();
DROP TRIGGER IF EXISTS restamp_txid ON home_game_card;
CREATE TRIGGER restamp_txid BEFORE UPDATE ON home_game_card
  FOR EACH ROW EXECUTE FUNCTION restamp_txid();
DROP TRIGGER IF EXISTS restamp_txid ON matches_game_card;
CREATE TRIGGER restamp_txid BEFORE UPDATE ON matches_game_card
  FOR EACH ROW EXECUTE FUNCTION restamp_txid();
DROP TRIGGER IF EXISTS restamp_txid ON editor;
CREATE TRIGGER restamp_txid BEFORE UPDATE ON editor
  FOR EACH ROW EXECUTE FUNCTION restamp_txid();

COMMIT;
