-- generated by pronto from program.cue — do not edit
SET lock_timeout = '5s';
SET statement_timeout = '60s';

BEGIN;

-- tier: container
DO $$ DECLARE t text; BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'golaberto_cdc') THEN
    CREATE PUBLICATION golaberto_cdc FOR TABLE app_user,category,championship,phase,stage_group,zone,stadium,team,team_group,referee,player,team_player,game,goal,player_game,comment,editor WITH (publish_generated_columns = stored);
  END IF;
  FOREACH t IN ARRAY ARRAY['app_user','category','championship','phase','stage_group','zone','stadium','team','team_group','referee','player','team_player','game','goal','player_game','comment','editor'] LOOP
    IF NOT EXISTS (SELECT 1 FROM pg_publication_tables
                   WHERE pubname = 'golaberto_cdc' AND schemaname = 'public' AND tablename = t) THEN
      EXECUTE format('ALTER PUBLICATION golaberto_cdc ADD TABLE %I', t);
    END IF;
  END LOOP;
END $$;
-- tier: any

-- Electric's own publication, declared rather than left to it.
-- ELECTRIC_MANUAL_TABLE_PUBLISHING makes it validate this instead of
-- building one, which is what lets its role hold only REPLICATION and
-- SELECT: creating a publication needs CREATE on the database, and
-- adding a table to one needs ownership of that table. A sync service
-- that owns the app's tables can drop them.
-- tier: container
DO $$ DECLARE t text; BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'electric_publication_default') THEN
    CREATE PUBLICATION electric_publication_default FOR TABLE app_user,category,championship,phase,stage_group,zone,stadium,team,team_group,referee,player,team_player,game,goal,player_game,standing,team_chance,zone_chance,position_chance,game_importance,team_rating,player_rating,rating_eval,game_card,home_game_card,team_game,comment,editor,player_stat,phase_round WITH (publish_generated_columns = stored);
  END IF;
  FOREACH t IN ARRAY ARRAY['app_user','category','championship','phase','stage_group','zone','stadium','team','team_group','referee','player','team_player','game','goal','player_game','standing','team_chance','zone_chance','position_chance','game_importance','team_rating','player_rating','rating_eval','game_card','home_game_card','team_game','comment','editor','player_stat','phase_round'] LOOP
    IF NOT EXISTS (SELECT 1 FROM pg_publication_tables
                   WHERE pubname = 'electric_publication_default' AND schemaname = 'public' AND tablename = t) THEN
      EXECUTE format('ALTER PUBLICATION electric_publication_default ADD TABLE %I', t);
    END IF;
  END LOOP;
END $$;

ALTER TABLE app_user REPLICA IDENTITY FULL;
ALTER TABLE category REPLICA IDENTITY FULL;
ALTER TABLE championship REPLICA IDENTITY FULL;
ALTER TABLE phase REPLICA IDENTITY FULL;
ALTER TABLE stage_group REPLICA IDENTITY FULL;
ALTER TABLE zone REPLICA IDENTITY FULL;
ALTER TABLE stadium REPLICA IDENTITY FULL;
ALTER TABLE team REPLICA IDENTITY FULL;
ALTER TABLE team_group REPLICA IDENTITY FULL;
ALTER TABLE referee REPLICA IDENTITY FULL;
ALTER TABLE player REPLICA IDENTITY FULL;
ALTER TABLE team_player REPLICA IDENTITY FULL;
ALTER TABLE game REPLICA IDENTITY FULL;
ALTER TABLE goal REPLICA IDENTITY FULL;
ALTER TABLE player_game REPLICA IDENTITY FULL;
ALTER TABLE standing REPLICA IDENTITY FULL;
ALTER TABLE team_chance REPLICA IDENTITY FULL;
ALTER TABLE zone_chance REPLICA IDENTITY FULL;
ALTER TABLE position_chance REPLICA IDENTITY FULL;
ALTER TABLE game_importance REPLICA IDENTITY FULL;
ALTER TABLE team_rating REPLICA IDENTITY FULL;
ALTER TABLE player_rating REPLICA IDENTITY FULL;
ALTER TABLE rating_eval REPLICA IDENTITY FULL;
ALTER TABLE game_card REPLICA IDENTITY FULL;
ALTER TABLE home_game_card REPLICA IDENTITY FULL;
ALTER TABLE team_game REPLICA IDENTITY FULL;
ALTER TABLE comment REPLICA IDENTITY FULL;
ALTER TABLE editor REPLICA IDENTITY FULL;
ALTER TABLE player_stat REPLICA IDENTITY FULL;
ALTER TABLE phase_round REPLICA IDENTITY FULL;
-- tier: any
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO anon;

COMMIT;
