-- generated by pronto from program.cue — do not edit
SET lock_timeout = '5s';
SET statement_timeout = '60s';

BEGIN;

CALL rls_protect('app_user');
ALTER TABLE app_user ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS app_user_app_user_select ON app_user;
CREATE POLICY app_user_app_user_select ON app_user FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS app_user_service_all ON app_user;
CREATE POLICY app_user_service_all ON app_user FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('category');
ALTER TABLE category ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS category_app_user_select ON category;
CREATE POLICY category_app_user_select ON category FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS category_service_all ON category;
CREATE POLICY category_service_all ON category FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('championship');
ALTER TABLE championship ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS championship_app_user_select ON championship;
CREATE POLICY championship_app_user_select ON championship FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS championship_service_all ON championship;
CREATE POLICY championship_service_all ON championship FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('home_championship');
ALTER TABLE home_championship ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS home_championship_app_user_select ON home_championship;
CREATE POLICY home_championship_app_user_select ON home_championship FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS home_championship_service_all ON home_championship;
CREATE POLICY home_championship_service_all ON home_championship FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('phase');
ALTER TABLE phase ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS phase_app_user_select ON phase;
CREATE POLICY phase_app_user_select ON phase FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS phase_service_all ON phase;
CREATE POLICY phase_service_all ON phase FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('stage_group');
ALTER TABLE stage_group ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS stage_group_app_user_select ON stage_group;
CREATE POLICY stage_group_app_user_select ON stage_group FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS stage_group_service_all ON stage_group;
CREATE POLICY stage_group_service_all ON stage_group FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('zone');
ALTER TABLE zone ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS zone_app_user_select ON zone;
CREATE POLICY zone_app_user_select ON zone FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS zone_service_all ON zone;
CREATE POLICY zone_service_all ON zone FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('stadium');
ALTER TABLE stadium ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS stadium_app_user_select ON stadium;
CREATE POLICY stadium_app_user_select ON stadium FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS stadium_service_all ON stadium;
CREATE POLICY stadium_service_all ON stadium FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('team');
ALTER TABLE team ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS team_app_user_select ON team;
CREATE POLICY team_app_user_select ON team FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS team_service_all ON team;
CREATE POLICY team_service_all ON team FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('team_championship');
ALTER TABLE team_championship ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS team_championship_app_user_select ON team_championship;
CREATE POLICY team_championship_app_user_select ON team_championship FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS team_championship_service_all ON team_championship;
CREATE POLICY team_championship_service_all ON team_championship FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('team_group');
ALTER TABLE team_group ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS team_group_app_user_select ON team_group;
CREATE POLICY team_group_app_user_select ON team_group FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS team_group_service_all ON team_group;
CREATE POLICY team_group_service_all ON team_group FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('referee');
ALTER TABLE referee ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS referee_app_user_select ON referee;
CREATE POLICY referee_app_user_select ON referee FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS referee_service_all ON referee;
CREATE POLICY referee_service_all ON referee FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('geography_region');
ALTER TABLE geography_region ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS geography_region_app_user_select ON geography_region;
CREATE POLICY geography_region_app_user_select ON geography_region FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS geography_region_service_all ON geography_region;
CREATE POLICY geography_region_service_all ON geography_region FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('geography_country');
ALTER TABLE geography_country ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS geography_country_app_user_select ON geography_country;
CREATE POLICY geography_country_app_user_select ON geography_country FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS geography_country_service_all ON geography_country;
CREATE POLICY geography_country_service_all ON geography_country FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('team_directory');
ALTER TABLE team_directory ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS team_directory_app_user_select ON team_directory;
CREATE POLICY team_directory_app_user_select ON team_directory FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS team_directory_service_all ON team_directory;
CREATE POLICY team_directory_service_all ON team_directory FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('player');
ALTER TABLE player ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS player_app_user_select ON player;
CREATE POLICY player_app_user_select ON player FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS player_service_all ON player;
CREATE POLICY player_service_all ON player FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('team_player');
ALTER TABLE team_player ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS team_player_app_user_select ON team_player;
CREATE POLICY team_player_app_user_select ON team_player FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS team_player_service_all ON team_player;
CREATE POLICY team_player_service_all ON team_player FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('team_roster');
ALTER TABLE team_roster ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS team_roster_app_user_select ON team_roster;
CREATE POLICY team_roster_app_user_select ON team_roster FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS team_roster_service_all ON team_roster;
CREATE POLICY team_roster_service_all ON team_roster FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('team_player_history');
ALTER TABLE team_player_history ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS team_player_history_app_user_select ON team_player_history;
CREATE POLICY team_player_history_app_user_select ON team_player_history FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS team_player_history_service_all ON team_player_history;
CREATE POLICY team_player_history_service_all ON team_player_history FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('game');
ALTER TABLE game ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS game_app_user_select ON game;
CREATE POLICY game_app_user_select ON game FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS game_service_all ON game;
CREATE POLICY game_service_all ON game FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('goal');
ALTER TABLE goal ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS goal_app_user_select ON goal;
CREATE POLICY goal_app_user_select ON goal FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS goal_service_all ON goal;
CREATE POLICY goal_service_all ON goal FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('player_game');
ALTER TABLE player_game ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS player_game_app_user_select ON player_game;
CREATE POLICY player_game_app_user_select ON player_game FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS player_game_service_all ON player_game;
CREATE POLICY player_game_service_all ON player_game FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('standing');
ALTER TABLE standing ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS standing_app_user_select ON standing;
CREATE POLICY standing_app_user_select ON standing FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS standing_service_all ON standing;
CREATE POLICY standing_service_all ON standing FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('team_chance');
ALTER TABLE team_chance ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS team_chance_app_user_select ON team_chance;
CREATE POLICY team_chance_app_user_select ON team_chance FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS team_chance_service_all ON team_chance;
CREATE POLICY team_chance_service_all ON team_chance FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('zone_chance');
ALTER TABLE zone_chance ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS zone_chance_app_user_select ON zone_chance;
CREATE POLICY zone_chance_app_user_select ON zone_chance FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS zone_chance_service_all ON zone_chance;
CREATE POLICY zone_chance_service_all ON zone_chance FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('position_chance');
ALTER TABLE position_chance ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS position_chance_app_user_select ON position_chance;
CREATE POLICY position_chance_app_user_select ON position_chance FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS position_chance_service_all ON position_chance;
CREATE POLICY position_chance_service_all ON position_chance FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('game_importance');
ALTER TABLE game_importance ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS game_importance_app_user_select ON game_importance;
CREATE POLICY game_importance_app_user_select ON game_importance FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS game_importance_service_all ON game_importance;
CREATE POLICY game_importance_service_all ON game_importance FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('team_rating');
ALTER TABLE team_rating ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS team_rating_app_user_select ON team_rating;
CREATE POLICY team_rating_app_user_select ON team_rating FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS team_rating_service_all ON team_rating;
CREATE POLICY team_rating_service_all ON team_rating FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('player_rating');
ALTER TABLE player_rating ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS player_rating_app_user_select ON player_rating;
CREATE POLICY player_rating_app_user_select ON player_rating FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS player_rating_service_all ON player_rating;
CREATE POLICY player_rating_service_all ON player_rating FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('rating_eval');
ALTER TABLE rating_eval ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rating_eval_app_user_select ON rating_eval;
CREATE POLICY rating_eval_app_user_select ON rating_eval FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS rating_eval_service_all ON rating_eval;
CREATE POLICY rating_eval_service_all ON rating_eval FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('game_card');
ALTER TABLE game_card ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS game_card_app_user_select ON game_card;
CREATE POLICY game_card_app_user_select ON game_card FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS game_card_service_all ON game_card;
CREATE POLICY game_card_service_all ON game_card FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('home_game_card');
ALTER TABLE home_game_card ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS home_game_card_app_user_select ON home_game_card;
CREATE POLICY home_game_card_app_user_select ON home_game_card FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS home_game_card_service_all ON home_game_card;
CREATE POLICY home_game_card_service_all ON home_game_card FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('matches_game_card');
ALTER TABLE matches_game_card ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS matches_game_card_app_user_select ON matches_game_card;
CREATE POLICY matches_game_card_app_user_select ON matches_game_card FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS matches_game_card_service_all ON matches_game_card;
CREATE POLICY matches_game_card_service_all ON matches_game_card FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('team_game');
ALTER TABLE team_game ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS team_game_app_user_select ON team_game;
CREATE POLICY team_game_app_user_select ON team_game FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS team_game_service_all ON team_game;
CREATE POLICY team_game_service_all ON team_game FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('comment');
ALTER TABLE comment ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS comment_app_user_select ON comment;
CREATE POLICY comment_app_user_select ON comment FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS comment_service_all ON comment;
CREATE POLICY comment_service_all ON comment FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('editor');
ALTER TABLE editor ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS editor_app_user_select ON editor;
CREATE POLICY editor_app_user_select ON editor FOR SELECT TO app_user USING (editor.app_user_id = auth_uid());
DROP POLICY IF EXISTS editor_app_user_insert ON editor;
CREATE POLICY editor_app_user_insert ON editor FOR INSERT TO app_user WITH CHECK (editor.app_user_id = auth_uid());
DROP POLICY IF EXISTS editor_app_user_update ON editor;
CREATE POLICY editor_app_user_update ON editor FOR UPDATE TO app_user USING (editor.app_user_id = auth_uid());
DROP POLICY IF EXISTS editor_app_user_delete ON editor;
CREATE POLICY editor_app_user_delete ON editor FOR DELETE TO app_user USING (editor.app_user_id = auth_uid());
DROP POLICY IF EXISTS editor_service_all ON editor;
CREATE POLICY editor_service_all ON editor FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('player_stat');
ALTER TABLE player_stat ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS player_stat_app_user_select ON player_stat;
CREATE POLICY player_stat_app_user_select ON player_stat FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS player_stat_service_all ON player_stat;
CREATE POLICY player_stat_service_all ON player_stat FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('phase_round');
ALTER TABLE phase_round ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS phase_round_app_user_select ON phase_round;
CREATE POLICY phase_round_app_user_select ON phase_round FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS phase_round_service_all ON phase_round;
CREATE POLICY phase_round_service_all ON phase_round FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('team_comment');
ALTER TABLE team_comment ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS team_comment_app_user_select ON team_comment;
CREATE POLICY team_comment_app_user_select ON team_comment FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS team_comment_service_all ON team_comment;
CREATE POLICY team_comment_service_all ON team_comment FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('team_campaign_point');
ALTER TABLE team_campaign_point ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS team_campaign_point_app_user_select ON team_campaign_point;
CREATE POLICY team_campaign_point_app_user_select ON team_campaign_point FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS team_campaign_point_service_all ON team_campaign_point;
CREATE POLICY team_campaign_point_service_all ON team_campaign_point FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('team_odds_history');
ALTER TABLE team_odds_history ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS team_odds_history_app_user_select ON team_odds_history;
CREATE POLICY team_odds_history_app_user_select ON team_odds_history FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS team_odds_history_service_all ON team_odds_history;
CREATE POLICY team_odds_history_service_all ON team_odds_history FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('team_rating_chart');
ALTER TABLE team_rating_chart ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS team_rating_chart_app_user_select ON team_rating_chart;
CREATE POLICY team_rating_chart_app_user_select ON team_rating_chart FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS team_rating_chart_service_all ON team_rating_chart;
CREATE POLICY team_rating_chart_service_all ON team_rating_chart FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('team_odds_chart');
ALTER TABLE team_odds_chart ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS team_odds_chart_app_user_select ON team_odds_chart;
CREATE POLICY team_odds_chart_app_user_select ON team_odds_chart FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS team_odds_chart_service_all ON team_odds_chart;
CREATE POLICY team_odds_chart_service_all ON team_odds_chart FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('team_roster_total');
ALTER TABLE team_roster_total ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS team_roster_total_app_user_select ON team_roster_total;
CREATE POLICY team_roster_total_app_user_select ON team_roster_total FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS team_roster_total_service_all ON team_roster_total;
CREATE POLICY team_roster_total_service_all ON team_roster_total FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('community_access');
ALTER TABLE community_access ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS community_access_app_user_select ON community_access;
CREATE POLICY community_access_app_user_select ON community_access FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS community_access_service_all ON community_access;
CREATE POLICY community_access_service_all ON community_access FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('match_probability');
ALTER TABLE match_probability ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS match_probability_app_user_select ON match_probability;
CREATE POLICY match_probability_app_user_select ON match_probability FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS match_probability_service_all ON match_probability;
CREATE POLICY match_probability_service_all ON match_probability FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('match_recent_result');
ALTER TABLE match_recent_result ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS match_recent_result_app_user_select ON match_recent_result;
CREATE POLICY match_recent_result_app_user_select ON match_recent_result FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS match_recent_result_service_all ON match_recent_result;
CREATE POLICY match_recent_result_service_all ON match_recent_result FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('phase_clone');
ALTER TABLE phase_clone ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS phase_clone_app_user_select ON phase_clone;
CREATE POLICY phase_clone_app_user_select ON phase_clone FOR SELECT TO app_user USING (phase_clone.app_user_id = auth_uid());
DROP POLICY IF EXISTS phase_clone_app_user_insert ON phase_clone;
CREATE POLICY phase_clone_app_user_insert ON phase_clone FOR INSERT TO app_user WITH CHECK (phase_clone.app_user_id = auth_uid());
DROP POLICY IF EXISTS phase_clone_app_user_update ON phase_clone;
CREATE POLICY phase_clone_app_user_update ON phase_clone FOR UPDATE TO app_user USING (phase_clone.app_user_id = auth_uid());
DROP POLICY IF EXISTS phase_clone_app_user_delete ON phase_clone;
CREATE POLICY phase_clone_app_user_delete ON phase_clone FOR DELETE TO app_user USING (phase_clone.app_user_id = auth_uid());
DROP POLICY IF EXISTS phase_clone_service_all ON phase_clone;
CREATE POLICY phase_clone_service_all ON phase_clone FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('player_merge');
ALTER TABLE player_merge ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS player_merge_app_user_select ON player_merge;
CREATE POLICY player_merge_app_user_select ON player_merge FOR SELECT TO app_user USING (player_merge.app_user_id = auth_uid());
DROP POLICY IF EXISTS player_merge_app_user_insert ON player_merge;
CREATE POLICY player_merge_app_user_insert ON player_merge FOR INSERT TO app_user WITH CHECK (player_merge.app_user_id = auth_uid());
DROP POLICY IF EXISTS player_merge_app_user_update ON player_merge;
CREATE POLICY player_merge_app_user_update ON player_merge FOR UPDATE TO app_user USING (player_merge.app_user_id = auth_uid());
DROP POLICY IF EXISTS player_merge_app_user_delete ON player_merge;
CREATE POLICY player_merge_app_user_delete ON player_merge FOR DELETE TO app_user USING (player_merge.app_user_id = auth_uid());
DROP POLICY IF EXISTS player_merge_service_all ON player_merge;
CREATE POLICY player_merge_service_all ON player_merge FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('user_biography');
ALTER TABLE user_biography ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS user_biography_app_user_select ON user_biography;
CREATE POLICY user_biography_app_user_select ON user_biography FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS user_biography_service_all ON user_biography;
CREATE POLICY user_biography_service_all ON user_biography FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('game_change');
ALTER TABLE game_change ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS game_change_app_user_select ON game_change;
CREATE POLICY game_change_app_user_select ON game_change FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS game_change_service_all ON game_change;
CREATE POLICY game_change_service_all ON game_change FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('user_directory');
ALTER TABLE user_directory ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS user_directory_app_user_select ON user_directory;
CREATE POLICY user_directory_app_user_select ON user_directory FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS user_directory_service_all ON user_directory;
CREATE POLICY user_directory_service_all ON user_directory FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('match_head_to_head');
ALTER TABLE match_head_to_head ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS match_head_to_head_app_user_select ON match_head_to_head;
CREATE POLICY match_head_to_head_app_user_select ON match_head_to_head FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS match_head_to_head_service_all ON match_head_to_head;
CREATE POLICY match_head_to_head_service_all ON match_head_to_head FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('match_lineup');
ALTER TABLE match_lineup ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS match_lineup_app_user_select ON match_lineup;
CREATE POLICY match_lineup_app_user_select ON match_lineup FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS match_lineup_service_all ON match_lineup;
CREATE POLICY match_lineup_service_all ON match_lineup FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('match_location');
ALTER TABLE match_location ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS match_location_app_user_select ON match_location;
CREATE POLICY match_location_app_user_select ON match_location FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS match_location_service_all ON match_location;
CREATE POLICY match_location_service_all ON match_location FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('user_avatar');
ALTER TABLE user_avatar ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS user_avatar_app_user_select ON user_avatar;
CREATE POLICY user_avatar_app_user_select ON user_avatar FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS user_avatar_service_all ON user_avatar;
CREATE POLICY user_avatar_service_all ON user_avatar FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('user_pending_upload');
ALTER TABLE user_pending_upload ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS user_pending_upload_app_user_select ON user_pending_upload;
CREATE POLICY user_pending_upload_app_user_select ON user_pending_upload FOR SELECT TO app_user USING (user_pending_upload.app_user_id = auth_uid());
DROP POLICY IF EXISTS user_pending_upload_app_user_insert ON user_pending_upload;
CREATE POLICY user_pending_upload_app_user_insert ON user_pending_upload FOR INSERT TO app_user WITH CHECK (user_pending_upload.app_user_id = auth_uid());
DROP POLICY IF EXISTS user_pending_upload_app_user_update ON user_pending_upload;
CREATE POLICY user_pending_upload_app_user_update ON user_pending_upload FOR UPDATE TO app_user USING (user_pending_upload.app_user_id = auth_uid());
DROP POLICY IF EXISTS user_pending_upload_app_user_delete ON user_pending_upload;
CREATE POLICY user_pending_upload_app_user_delete ON user_pending_upload FOR DELETE TO app_user USING (user_pending_upload.app_user_id = auth_uid());
DROP POLICY IF EXISTS user_pending_upload_service_all ON user_pending_upload;
CREATE POLICY user_pending_upload_service_all ON user_pending_upload FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('team_odds_progress');
ALTER TABLE team_odds_progress ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS team_odds_progress_app_user_select ON team_odds_progress;
CREATE POLICY team_odds_progress_app_user_select ON team_odds_progress FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS team_odds_progress_service_all ON team_odds_progress;
CREATE POLICY team_odds_progress_service_all ON team_odds_progress FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('phase_directory');
ALTER TABLE phase_directory ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS phase_directory_app_user_select ON phase_directory;
CREATE POLICY phase_directory_app_user_select ON phase_directory FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS phase_directory_service_all ON phase_directory;
CREATE POLICY phase_directory_service_all ON phase_directory FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('player_directory');
ALTER TABLE player_directory ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS player_directory_app_user_select ON player_directory;
CREATE POLICY player_directory_app_user_select ON player_directory FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS player_directory_service_all ON player_directory;
CREATE POLICY player_directory_service_all ON player_directory FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('game_archive');
ALTER TABLE game_archive ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS game_archive_app_user_select ON game_archive;
CREATE POLICY game_archive_app_user_select ON game_archive FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS game_archive_service_all ON game_archive;
CREATE POLICY game_archive_service_all ON game_archive FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('player_appearance');
ALTER TABLE player_appearance ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS player_appearance_app_user_select ON player_appearance;
CREATE POLICY player_appearance_app_user_select ON player_appearance FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS player_appearance_service_all ON player_appearance;
CREATE POLICY player_appearance_service_all ON player_appearance FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('championship_attendance');
ALTER TABLE championship_attendance ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS championship_attendance_app_user_select ON championship_attendance;
CREATE POLICY championship_attendance_app_user_select ON championship_attendance FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS championship_attendance_service_all ON championship_attendance;
CREATE POLICY championship_attendance_service_all ON championship_attendance FOR ALL TO service USING (true) WITH CHECK (true);

COMMIT;
